// Generated by scripts/ambitions-token-generate.py
// Source manifest hash: 7e080c08ea5d211a71b5ccd60f1991f1ff2f6324d5682f276bbb4c9d5c2fb048
// Do not edit by hand.


import Foundation

public struct AmbitionObjectToken: Codable, Sendable {
    public let name: String
    public let surface: String
    public let primaryToken: String
    public let states: [String]
    public let proof: String
    public init(name: String, surface: String, primaryToken: String, states: [String], proof: String) {
        self.name = name
        self.surface = surface
        self.primaryToken = primaryToken
        self.states = states
        self.proof = proof
    }
}

public enum AmbitionObjectTokens {
    public static let realityMeridian: AmbitionObjectToken = .init(name: "RealityMeridian", surface: "Today", primaryToken: "todayFocus", states: ["clear day", "recovery day", "high pressure", "stale source", "protected time", "no schedule data"], proof: "source / proof / receipt clarity")
    public static let constellationAtlas: AmbitionObjectToken = .init(name: "ConstellationAtlas", surface: "Goals", primaryToken: "goalThread", states: ["empty", "active threads", "proof gap", "blocker", "pivot", "recovery"], proof: "goal-thread and proof-gap traceability")
    public static let atmosphereComposer: AmbitionObjectToken = .init(name: "AtmosphereComposer", surface: "Capture", primaryToken: "captureSignal", states: ["idle", "active text", "route reveal", "held with dignity", "proof attached", "wrong-route recovery"], proof: "capture routing and correction path")
    public static let lifeshapeField: AmbitionObjectToken = .init(name: "LifeshapeField", surface: "Time", primaryToken: "timeCapacity", states: ["day capacity", "week pressure", "month life shape", "protected conflict", "reflow preview", "stale source", "away / vacation"], proof: "capacity and protected-time semantics")
    public static let userSystemProfile: AmbitionObjectToken = .init(name: "UserSystemProfile", surface: "You", primaryToken: "youTrust", states: ["runtime trust", "automation ladder", "learned pattern", "privacy", "reset / forget preview"], proof: "local learning and trust controls")
}
