// Generated by scripts/ambitions-token-generate.py
// Source manifest hash: 7e080c08ea5d211a71b5ccd60f1991f1ff2f6324d5682f276bbb4c9d5c2fb048
// Do not edit by hand.


import Foundation

public struct AmbitionTokenColor: Codable, Sendable {
    public let name: String
    public let hex: String
    public let meaning: String
    public init(name: String, hex: String, meaning: String) {
        self.name = name
        self.hex = hex
        self.meaning = meaning
    }
}

public struct AmbitionTokenMeasure: Codable, Sendable {
    public let name: String
    public let value: Double
    public let meaning: String
    public init(name: String, value: Double, meaning: String) {
        self.name = name
        self.value = value
        self.meaning = meaning
    }
}

public struct AmbitionTokenLayout: Codable, Sendable {
    public let name: String
    public let radius: Double
    public let padding: Double
    public let meaning: String
    public init(name: String, radius: Double, padding: Double, meaning: String) {
        self.name = name
        self.radius = radius
        self.padding = padding
        self.meaning = meaning
    }
}

public struct AmbitionTokenText: Codable, Sendable {
    public let name: String
    public let value: String
    public let meaning: String
    public init(name: String, value: String, meaning: String) {
        self.name = name
        self.value = value
        self.meaning = meaning
    }
}

public enum AmbitionTokens {
    public enum Foundation {
        public static let graphiteInk: AmbitionTokenColor = .init(name: "graphiteInk", hex: "#0F1114", meaning: "quiet luxury base surface")
        public static let graphiteRise: AmbitionTokenColor = .init(name: "graphiteRise", hex: "#171A1F", meaning: "resting elevated surface")
        public static let warmPaper: AmbitionTokenColor = .init(name: "warmPaper", hex: "#E8E3DB", meaning: "light canvas")
        public static let warmMist: AmbitionTokenColor = .init(name: "warmMist", hex: "#F3EEE8", meaning: "light elevated canvas")
        public static let luminousTrace: AmbitionTokenColor = .init(name: "luminousTrace", hex: "#C8A96B", meaning: "live trace and receipt highlight")
        public static let celestialField: AmbitionTokenColor = .init(name: "celestialField", hex: "#141A24", meaning: "deep field surface")
        public static let quietGlass: AmbitionTokenColor = .init(name: "quietGlass", hex: "#202838", meaning: "overlay surface with restraint")
        public static let recoveryMint: AmbitionTokenColor = .init(name: "recoveryMint", hex: "#8BC6A8", meaning: "recovery and repaired state")
    }

    public enum Semantic {
        public static let todayFocus: AmbitionTokenColor = .init(name: "todayFocus", hex: "#C8A96B", meaning: "today attention surface")
        public static let goalThread: AmbitionTokenColor = .init(name: "goalThread", hex: "#A9C0D6", meaning: "goal-thread linkage")
        public static let captureSignal: AmbitionTokenColor = .init(name: "captureSignal", hex: "#D29D72", meaning: "capture entry and placement preview")
        public static let timeCapacity: AmbitionTokenColor = .init(name: "timeCapacity", hex: "#89A4C2", meaning: "capacity and pressure")
        public static let youTrust: AmbitionTokenColor = .init(name: "youTrust", hex: "#C6A3D4", meaning: "trust seam and local runtime")
        public static let sourceFreshness: AmbitionTokenColor = .init(name: "sourceFreshness", hex: "#8AC6B8", meaning: "freshness and staleness")
        public static let proofReceipt: AmbitionTokenColor = .init(name: "proofReceipt", hex: "#D4BC7D", meaning: "proof and receipt surface")
        public static let protectedTime: AmbitionTokenColor = .init(name: "protectedTime", hex: "#8DA3D9", meaning: "protected time and conflict")
    }

    public enum Component {
        public static let panelHero: AmbitionTokenLayout = .init(name: "panelHero", radius: 30, padding: 24, meaning: "hero object panel")
        public static let panelStandard: AmbitionTokenLayout = .init(name: "panelStandard", radius: 24, padding: 20, meaning: "standard rich panel")
        public static let panelCompact: AmbitionTokenLayout = .init(name: "panelCompact", radius: 18, padding: 16, meaning: "dense secondary panel")
        public static let ctaPrimary: AmbitionTokenLayout = .init(name: "ctaPrimary", radius: 999, padding: 16, meaning: "primary action")
        public static let ctaSecondary: AmbitionTokenLayout = .init(name: "ctaSecondary", radius: 18, padding: 14, meaning: "secondary action")
        public static let disclosureRow: AmbitionTokenLayout = .init(name: "disclosureRow", radius: 16, padding: 12, meaning: "source / proof / receipt row")
        public static let proofChip: AmbitionTokenLayout = .init(name: "proofChip", radius: 16, padding: 10, meaning: "proof summary chip")
        public static let sourceBadge: AmbitionTokenLayout = .init(name: "sourceBadge", radius: 999, padding: 10, meaning: "source freshness badge")
    }

    public enum Motion {
        public static let micro: AmbitionTokenMeasure = .init(name: "micro", value: 0.12, meaning: "micro feedback")
        public static let regular: AmbitionTokenMeasure = .init(name: "regular", value: 0.22, meaning: "standard object transition")
        public static let emphasis: AmbitionTokenMeasure = .init(name: "emphasis", value: 0.3, meaning: "important emphasis")
        public static let route: AmbitionTokenMeasure = .init(name: "route", value: 0.28, meaning: "route change")
        public static let settle: AmbitionTokenMeasure = .init(name: "settle", value: 0.18, meaning: "settle animation")
    }

    public enum Accessibility {
        public static let minimumTapTarget: AmbitionTokenText = .init(name: "minimumTapTarget", value: "44", meaning: "minimum tap target")
        public static let textScaleFloor: AmbitionTokenText = .init(name: "textScaleFloor", value: "Large", meaning: "supports dynamic type")
        public static let reduceMotionFallback: AmbitionTokenText = .init(name: "reduceMotionFallback", value: "fade", meaning: "motion fallback")
        public static let contrastFallback: AmbitionTokenText = .init(name: "contrastFallback", value: "elevated stroke", meaning: "contrast fallback")
        public static let differentiationFallback: AmbitionTokenText = .init(name: "differentiationFallback", value: "icon plus label", meaning: "color-independent meaning")
        public static let voiceOverOrder: AmbitionTokenText = .init(name: "voiceOverOrder", value: "surface, source, proof, receipt, action", meaning: "reading order")
    }

    public enum Haptics {
        public static let selection: AmbitionTokenText = .init(name: "selection", value: "selection", meaning: "selection")
        public static let completion: AmbitionTokenText = .init(name: "completion", value: "completion", meaning: "completion")
        public static let correction: AmbitionTokenText = .init(name: "correction", value: "correction", meaning: "correction")
        public static let reschedule: AmbitionTokenText = .init(name: "reschedule", value: "reschedule", meaning: "reschedule")
        public static let routeChange: AmbitionTokenText = .init(name: "routeChange", value: "route change", meaning: "route change")
        public static let warning: AmbitionTokenText = .init(name: "warning", value: "warning", meaning: "warning")
    }

}
