// Generated by scripts/ambitions-token-generate.py
// Source manifest hash: 7e080c08ea5d211a71b5ccd60f1991f1ff2f6324d5682f276bbb4c9d5c2fb048
// Do not edit by hand.


import Foundation

public struct AmbitionStateToken: Codable, Sendable {
    public let name: String
    public let states: [String: String]
    public init(name: String, states: [String: String]) {
        self.name = name
        self.states = states
    }
}

public enum AmbitionStateTokens {
    public static let sourceFreshness: AmbitionStateToken = .init(name: "sourceFreshness", states: [
"live": "fresh and verified", "stale": "stale and needs refresh", "missing": "missing source"])
    public static let proof: AmbitionStateToken = .init(name: "proof", states: [
"strong": "proof attached", "partial": "proof gap", "none": "no proof yet"])
    public static let closure: AmbitionStateToken = .init(name: "closure", states: [
"closed": "closure recorded", "recovery": "recovery path open", "pivot": "pivot required"])
    public static let recovery: AmbitionStateToken = .init(name: "recovery", states: [
"gentle": "gentle recovery", "active": "active recovery", "reset": "reset or forget preview"])
    public static let protectedTime: AmbitionStateToken = .init(name: "protectedTime", states: [
"reserved": "protected time reserved", "conflict": "protected time conflict", "reschedule": "reschedule preview"])
}
