"""Foundry source registry and seed pathway catalog."""

from __future__ import annotations

SOURCE_REGISTRY = [
    {
        "id": "nara.constitution.presidency",
        "title": "U.S. Constitution presidential eligibility",
        "publisher": "National Archives",
        "url": "https://www.archives.gov/founding-docs/constitution-transcript",
        "authorityTier": "constitutional_primary",
        "license": "U.S. federal public source; cite source URL",
        "freshnessCadence": "watch for constitutional amendment or authoritative transcript update",
        "domains": ["civic", "law", "public_service", "eligibility"],
        "adapter": "official_static_page",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "nasa.astronaut.requirements",
        "title": "NASA astronaut candidate requirements",
        "publisher": "NASA",
        "url": "https://www.nasa.gov/humans-in-space/astronauts/astronaut-requirements/",
        "authorityTier": "official_program",
        "license": "NASA public web source; cite source URL",
        "freshnessCadence": "before and during each astronaut selection cycle",
        "domains": ["space", "career", "stem", "public_service", "eligibility"],
        "adapter": "official_static_page",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "nasa.astronaut.selection",
        "title": "NASA astronaut selection program",
        "publisher": "NASA",
        "url": "https://www.nasa.gov/humans-in-space/astronauts/astronaut-selection-program/",
        "authorityTier": "official_program",
        "license": "NASA public web source; cite source URL",
        "freshnessCadence": "before and during each selection cycle",
        "domains": ["space", "career", "training", "selection"],
        "adapter": "official_static_page",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "onet.database",
        "title": "O*NET database and Web Services",
        "publisher": "U.S. Department of Labor Employment and Training Administration",
        "url": "https://www.onetcenter.org/database.html",
        "authorityTier": "official_occupational_database",
        "license": "CC BY 4.0 with O*NET attribution requirements",
        "freshnessCadence": "track O*NET production releases and Database Services current version",
        "domains": [
            "occupation",
            "career_clusters",
            "skills",
            "essential_skills",
            "transferable_skills",
            "tasks",
            "work_activities",
            "interests",
            "job_zones",
            "education",
            "training",
            "knowledge",
            "abilities",
            "work_styles",
            "software_skills",
            "transfer",
        ],
        "adapter": "official_onet_text_database",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "bls.public.data.api",
        "title": "BLS Public Data API",
        "publisher": "U.S. Bureau of Labor Statistics",
        "url": "https://www.bls.gov/developers/home.htm",
        "authorityTier": "official_labor_statistics",
        "license": "U.S. federal public source; cite source URL",
        "freshnessCadence": "series-specific BLS publication schedule",
        "domains": ["labor_market", "wages", "employment", "occupation", "trend"],
        "adapter": "official_bls_public_api",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "wikidata.structured_crosswalk",
        "title": "Wikidata structured entity crosswalk",
        "publisher": "Wikidata / Wikimedia Foundation",
        "url": "https://www.wikidata.org/wiki/Wikidata:Data_access",
        "authorityTier": "structured_data_crosswalk",
        "license": "CC0 structured data; crosswalk only",
        "freshnessCadence": "bounded entity lookup or SPARQL crosswalk refresh; respect Wikimedia rate limits",
        "domains": ["source_crosswalk", "entity_alignment", "occupation", "skills", "scholarly_metadata"],
        "adapter": "official_wikidata_entity_crosswalk",
        "lastReviewed": "2026-06-27",
    },
    {
        "id": "openalex.works",
        "title": "OpenAlex scholarly metadata API",
        "publisher": "OpenAlex / OurResearch",
        "url": "https://api.openalex.org/works",
        "authorityTier": "scholarly_metadata_reference",
        "license": "OpenAlex public scholarly metadata; cite source URL and OpenAlex IDs",
        "freshnessCadence": "bounded public/reference metadata lookup; high-volume use requires approved budget and rate controls",
        "domains": ["scholarly_metadata", "research", "education", "source_discovery"],
        "adapter": "official_openalex_api",
        "lastReviewed": "2026-06-27",
    },
    {
        "id": "usajobs.search",
        "title": "USAJOBS current and historic job opportunity APIs",
        "publisher": "U.S. Office of Personnel Management",
        "url": "https://developer.usajobs.gov/api-reference/",
        "authorityTier": "official_public_job_announcements",
        "license": "public job announcement API; API key required for search APIs",
        "freshnessCadence": "daily or per source modified date",
        "domains": ["career", "federal_jobs", "requirements", "qualifications"],
        "adapter": "official_usajobs_authenticated_search",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "data.gov.catalog",
        "title": "Data.gov API v4 metadata search",
        "publisher": "U.S. General Services Administration",
        "url": "https://api.gsa.gov/technology/datagov/v4/search",
        "authorityTier": "source_of_sources_metadata",
        "license": "dataset-specific; catalog metadata only",
        "freshnessCadence": "agency harvest cadence from Data.gov metadata",
        "domains": ["source_discovery", "government_data", "metadata"],
        "adapter": "official_datagov_v4_search",
        "lastReviewed": "2026-06-25",
    },
    {
        "id": "college-scorecard.api",
        "title": "College Scorecard data API",
        "publisher": "U.S. Department of Education",
        "url": "https://collegescorecard.ed.gov/data/api-documentation/",
        "authorityTier": "official_education_data",
        "license": "U.S. Department of Education public data; cite source URL",
        "freshnessCadence": "track Scorecard changelog and data release date",
        "domains": ["education", "programs", "costs", "outcomes", "institutions"],
        "adapter": "official_college_scorecard_api",
        "lastReviewed": "2026-06-25",
    },
]


PRESIDENT_PATHWAY = {
    "id": "pathway.civic.us_president",
    "title": "Become eligible to serve as President of the United States",
    "domain": "civic",
    "sourceIDs": ["nara.constitution.presidency"],
    "requirements": [
        {
            "id": "requirement.president.minimum_age",
            "claimID": "claim.president.age_35",
            "gateType": "eligibility",
            "structuredRule": {"type": "minimum_age", "years": 35, "evaluation": "when_elected"},
        },
        {
            "id": "requirement.president.natural_born_citizen",
            "claimID": "claim.president.natural_born_citizen",
            "gateType": "eligibility",
            "structuredRule": {"type": "citizenship_status", "required": "natural_born_us_citizen"},
        },
        {
            "id": "requirement.president.residency",
            "claimID": "claim.president.residency_14_years",
            "gateType": "eligibility",
            "structuredRule": {"type": "residency_duration", "country": "US", "years": 14},
        },
    ],
    "claims": [
        {
            "id": "claim.president.age_35",
            "text": "The presidency has a minimum age eligibility gate of 35 years.",
            "claimType": "eligibility_rule",
            "state": "source_backed",
            "freshness": "stable_law_watch",
            "sourceIDs": ["nara.constitution.presidency"],
        },
        {
            "id": "claim.president.natural_born_citizen",
            "text": "The presidency requires natural-born U.S. citizenship.",
            "claimType": "eligibility_rule",
            "state": "source_backed",
            "freshness": "stable_law_watch",
            "sourceIDs": ["nara.constitution.presidency"],
        },
        {
            "id": "claim.president.residency_14_years",
            "text": "The presidency requires at least 14 years of U.S. residency.",
            "claimType": "eligibility_rule",
            "state": "source_backed",
            "freshness": "stable_law_watch",
            "sourceIDs": ["nara.constitution.presidency"],
        },
    ],
    "skillAtoms": [
        "constitutional_literacy",
        "public_speaking",
        "coalition_building",
        "civic_leadership",
        "policy_reasoning",
        "campaign_operations",
        "ethical_decision_making",
        "executive_communication",
    ],
    "milestones": [
        {
            "id": "president.age_waiting_path",
            "whenBlockedBy": "requirement.president.minimum_age",
            "title": "Build civic capital before legal age eligibility",
            "purpose": "Keep progress real while eligibility is time-locked.",
            "output": "age-gated path state with review date and skill-building lanes",
        },
        {
            "id": "president.local_service_ladder",
            "title": "Start with local public-service leadership",
            "purpose": "Convert ambition into public trust, operations, and service proof.",
            "output": "portfolio of civic leadership receipts and public communication practice",
        },
    ],
    "alternatePaths": [
        {
            "id": "alternate.governor",
            "title": "Governor or state executive leadership",
            "sharedSkillAtoms": ["public_speaking", "coalition_building", "policy_reasoning", "executive_communication"],
        },
        {
            "id": "alternate.public_policy_leader",
            "title": "Public policy or civic institution leader",
            "sharedSkillAtoms": ["constitutional_literacy", "policy_reasoning", "ethical_decision_making"],
        },
    ],
}


NASA_ASTRONAUT_PATHWAY = {
    "id": "pathway.career.nasa_astronaut",
    "title": "Become competitive for NASA astronaut candidacy",
    "domain": "career",
    "sourceIDs": ["nasa.astronaut.requirements", "nasa.astronaut.selection", "onet.database", "usajobs.search"],
    "requirements": [
        {
            "id": "requirement.astronaut.us_citizen",
            "claimID": "claim.astronaut.us_citizen",
            "gateType": "eligibility",
            "structuredRule": {"type": "citizenship_status", "required": "us_citizen"},
        },
        {
            "id": "requirement.astronaut.stem_masters_or_equivalent",
            "claimID": "claim.astronaut.stem_masters_or_equivalent",
            "gateType": "credential",
            "structuredRule": {
                "type": "education_or_equivalent",
                "acceptedPaths": ["stem_masters", "doctoral_work", "medical_degree", "test_pilot_school"],
            },
        },
        {
            "id": "requirement.astronaut.experience_or_pic_hours",
            "claimID": "claim.astronaut.experience_or_pic_hours",
            "gateType": "experience",
            "structuredRule": {
                "type": "professional_experience_or_pilot_hours",
                "professionalYearsMinimum": 2,
                "pilotInCommandHours": 1000,
                "freshnessReview": "selection-cycle-sensitive; re-fetch and diff official NASA requirements before promotion",
            },
        },
        {
            "id": "requirement.astronaut.long_duration_physical",
            "claimID": "claim.astronaut.long_duration_physical",
            "gateType": "medical_physical",
            "structuredRule": {"type": "program_physical", "program": "NASA long-duration flight astronaut physical"},
        },
    ],
    "claims": [
        {
            "id": "claim.astronaut.us_citizen",
            "text": "NASA astronaut candidates must be U.S. citizens.",
            "claimType": "eligibility_rule",
            "state": "source_backed",
            "freshness": "selection_cycle_watch",
            "sourceIDs": ["nasa.astronaut.requirements"],
        },
        {
            "id": "claim.astronaut.stem_masters_or_equivalent",
            "text": "NASA requires a STEM master's degree or accepted equivalent education path.",
            "claimType": "credential_rule",
            "state": "source_backed",
            "freshness": "selection_cycle_watch",
            "sourceIDs": ["nasa.astronaut.requirements"],
        },
        {
            "id": "claim.astronaut.experience_or_pic_hours",
            "text": "NASA requires related professional experience after qualifying education or pilot-in-command jet aircraft time.",
            "claimType": "experience_rule",
            "state": "source_backed",
            "freshness": "selection_cycle_watch",
            "sourceIDs": ["nasa.astronaut.requirements"],
        },
        {
            "id": "claim.astronaut.long_duration_physical",
            "text": "NASA astronaut candidates must pass the long-duration flight astronaut physical.",
            "claimType": "medical_physical_rule",
            "state": "source_backed",
            "freshness": "selection_cycle_watch",
            "sourceIDs": ["nasa.astronaut.requirements"],
        },
        {
            "id": "claim.astronaut.training_after_selection",
            "text": "Astronaut candidates complete a training period before becoming eligible for flight assignment.",
            "claimType": "selection_pipeline",
            "state": "source_backed",
            "freshness": "selection_cycle_watch",
            "sourceIDs": ["nasa.astronaut.selection"],
        },
    ],
    "skillAtoms": [
        "advanced_stem_reasoning",
        "systems_engineering",
        "operational_discipline",
        "flight_or_field_operations",
        "physical_readiness",
        "teamwork",
        "leadership",
        "technical_communication",
        "risk_management",
        "interview_readiness",
    ],
    "milestones": [
        {
            "id": "astronaut.foundation_stem_path",
            "title": "Build a credible STEM foundation",
            "purpose": "Map education, projects, and research into an astronaut-relevant capability stack.",
            "output": "credential and project trajectory with freshness-linked requirements",
        },
        {
            "id": "astronaut.operations_path",
            "title": "Accumulate high-trust operational experience",
            "purpose": "Convert skill into evidence through research, engineering, flight, field, medical, or mission operations work.",
            "output": "experience ledger and alternate-path transfer map",
        },
        {
            "id": "astronaut.selection_readiness",
            "title": "Prepare for selection gates, interviews, and physical readiness",
            "purpose": "Stage interviews, communications, physical standards, and application evidence without pretending selection is guaranteed.",
            "output": "selection-readiness review state and next review date",
        },
    ],
    "alternatePaths": [
        {
            "id": "alternate.aerospace_engineer",
            "title": "Aerospace engineer",
            "sharedSkillAtoms": ["advanced_stem_reasoning", "systems_engineering", "technical_communication", "risk_management"],
        },
        {
            "id": "alternate.test_pilot_or_flight_ops",
            "title": "Test pilot or flight operations leader",
            "sharedSkillAtoms": ["flight_or_field_operations", "operational_discipline", "risk_management", "teamwork"],
        },
        {
            "id": "alternate.mission_operations",
            "title": "NASA mission operations or flight controller path",
            "sharedSkillAtoms": ["systems_engineering", "operational_discipline", "teamwork", "technical_communication"],
        },
        {
            "id": "alternate.research_scientist",
            "title": "Research scientist in space-relevant field",
            "sharedSkillAtoms": ["advanced_stem_reasoning", "technical_communication", "risk_management"],
        },
    ],
}


PATHWAY_SEEDS = [PRESIDENT_PATHWAY, NASA_ASTRONAUT_PATHWAY]
