"""Machine-readable Source Atlas source terms registry."""

from __future__ import annotations

from typing import Any

from .adapter_sdk import DistributionPolicy, R2PackPolicy, validate_distribution_policy
from .model import PRIVACY_BOUNDARY, utc_now


TERMS_REGISTRY_VERSION = "source-atlas-terms-registry-v1"

PUBLIC_PACK_CLASSES = [
    "official_public_source",
    "public_reference_claim",
    "public_requirement",
    "public_provenance",
    "public_ontology",
    "public_atom_edge_lattice",
    "public_recipe",
    "public_freshness",
]

FORBIDDEN_ARTIFACT_CLASS_GROUPS = [
    "non_public_runtime_field",
    "user_supplied_content",
    "account_or_credential_material",
    "personal_behavior_or_history",
    "non_reference_artifact",
]


SOURCE_TERMS_REGISTRY: list[dict[str, Any]] = [
    {
        "source_id": "onet.database",
        "source_name": "O*NET Database and O*NET OnLine public occupational reference data",
        "publisher": "U.S. Department of Labor Employment and Training Administration / National Center for O*NET Development",
        "source_url": "https://www.onetcenter.org/database.html",
        "terms_url": "https://www.onetcenter.org/overview.html#data",
        "license": "Creative Commons Attribution 4.0 International",
        "license_version": "4.0",
        "authority_tier": "official_dataset",
        "domain": "occupation",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "download release archives politely; fixture tests use local snapshots",
        "freshness_cadence": "track O*NET production database releases and quarterly review",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "O*NET data must retain O*NET attribution and license notice.",
    },
    {
        "source_id": "bls.public.data.api",
        "source_name": "BLS Public Data API",
        "publisher": "U.S. Bureau of Labor Statistics",
        "source_url": "https://www.bls.gov/developers/",
        "terms_url": "https://www.bls.gov/developers/termsOfService.htm",
        "license": "U.S. federal public data; cite BLS as source",
        "license_version": "current public API terms",
        "authority_tier": "official_government",
        "domain": "labor_market",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": "v1_no_key; v2_key_required_for_registered_high-volume_access",
        "rate_limit_policy": "deterministic fixtures do not require secrets; live v2 requests must respect BLS limits",
        "freshness_cadence": "series-specific publication schedule",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
    },
    {
        "source_id": "wikidata.crosswalk",
        "source_name": "Wikidata entity data",
        "publisher": "Wikimedia Foundation / Wikidata community",
        "source_url": "https://www.wikidata.org/wiki/Wikidata:Main_Page",
        "terms_url": "https://www.wikidata.org/wiki/Wikidata:Licensing",
        "license": "Creative Commons CC0 public domain dedication",
        "license_version": "1.0",
        "authority_tier": "open_knowledge_graph",
        "domain": "entity_crosswalk",
        "jurisdiction": "global",
        "language": "multilingual",
        "attribution_required": False,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "use deterministic fixtures for tests; live lookups must respect Wikidata endpoint etiquette",
        "freshness_cadence": "weekly crosswalk refresh and conflict review",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
    },
    {
        "source_id": "openalex.dataset",
        "source_name": "OpenAlex dataset and API",
        "publisher": "OpenAlex",
        "source_url": "https://openalex.org/",
        "terms_url": "https://docs.openalex.org/download-all-data/openalex-snapshot",
        "license": "Creative Commons CC0 public domain dedication",
        "license_version": "1.0",
        "authority_tier": "official_dataset",
        "domain": "scholarly_reference",
        "jurisdiction": "global",
        "language": "en",
        "attribution_required": False,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": "optional free polite-pool email/API use; fixture tests require no key",
        "rate_limit_policy": "fixture tests offline; live API should use polite pool; bulk snapshot route represented offline",
        "freshness_cadence": "monthly snapshot or API freshness review",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
    },
    {
        "source_id": "openalex.works",
        "source_name": "OpenAlex Works API public scholarly metadata",
        "publisher": "OpenAlex",
        "source_url": "https://openalex.org/",
        "terms_url": "https://docs.openalex.org/download-all-data/openalex-snapshot",
        "license": "Creative Commons CC0 public domain dedication for OpenAlex metadata",
        "license_version": "1.0",
        "authority_tier": "scholarly_metadata",
        "domain": "scholarly_reference",
        "jurisdiction": "global",
        "language": "en",
        "attribution_required": False,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": "required for governed high-volume API use; fixture tests require no key",
        "rate_limit_policy": "fixture tests offline; live/high-volume API access requires explicit key/rate/budget governance",
        "freshness_cadence": "monthly snapshot or API freshness review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "OpenAlex metadata is represented as public scholarly reference metadata.",
    },
    {
        "source_id": "usajobs.search",
        "source_name": "USAJOBS current and historic job opportunity APIs",
        "publisher": "U.S. Office of Personnel Management",
        "source_url": "https://developer.usajobs.gov/api-reference/",
        "terms_url": "https://developer.usajobs.gov/",
        "license": "terms not verified for redistributable Source Atlas pack inclusion",
        "license_version": "unverified",
        "authority_tier": "restricted",
        "domain": "public_job_lookup",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.LOOKUP_ONLY_NOT_PACKABLE.value,
        "r2_pack_policy": R2PackPolicy.R2_BLOCKED.value,
        "derivatives_allowed": False,
        "api_key_required": True,
        "rate_limit_policy": "credentialed lookup only; no pack output without explicit terms review",
        "freshness_cadence": "lookup-time only",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "restricted_unverified",
        "allowed_artifact_classes": ["official_public_source", "public_provenance"],
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": True,
    },
    {
        "source_id": "nara.constitution.presidency",
        "source_name": "U.S. Constitution presidential eligibility",
        "publisher": "National Archives",
        "source_url": "https://www.archives.gov/founding-docs/constitution-transcript",
        "terms_url": "https://www.usa.gov/government-works",
        "license": "U.S. federal public source with citation required",
        "license_version": "current public government works posture",
        "authority_tier": "official_government",
        "domain": "public_civic_requirements",
        "jurisdiction": "US federal",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "stable law watch with quarterly review",
        "last_terms_reviewed": "2026-06-27",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the National Archives.",
    },
    {
        "source_id": "college-scorecard.api",
        "source_name": "College Scorecard data API",
        "publisher": "U.S. Department of Education",
        "source_url": "https://collegescorecard.ed.gov/data/",
        "terms_url": "https://collegescorecard.ed.gov/data/",
        "license": "Creative Commons Attribution via current data.ed.gov/Data.gov catalog metadata",
        "license_version": "Data.gov College Scorecard package extra license=http://www.opendefinition.org/licenses/cc-by",
        "authority_tier": "official_government",
        "domain": "education_credentialing",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": "optional demo/no-key lane; live/high-volume access gated by API governance registry",
        "rate_limit_policy": "fixture tests offline; live API access requires --live/--execute and API governance budget policy",
        "freshness_cadence": "College Scorecard release tracking and quarterly legal/terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the U.S. Department of Education College Scorecard.",
    },
    {
        "source_id": "westpoint.redbook.computer_science_major",
        "source_name": "United States Military Academy Redbook Computer Science major curriculum",
        "publisher": "United States Military Academy / West Point",
        "source_url": "https://catalog.westpoint.edu/academics/academic-programs/majors-minors/computer-science-major/",
        "terms_url": "https://catalog.westpoint.edu/",
        "license": "U.S. federal public source with citation required; West Point catalog footer permits reproduction/distribution of posted public information",
        "license_version": "current public catalog posture",
        "authority_tier": "official_institution",
        "domain": "education_credentialing",
        "jurisdiction": "US federal",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "catalog year review and quarterly institutional source re-check",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the United States Military Academy Redbook.",
    },
    {
        "source_id": "sba.business_guide.start_business",
        "source_name": "SBA 10 steps to start your business guide",
        "publisher": "U.S. Small Business Administration",
        "source_url": "https://www.sba.gov/business-guide/10-steps-start-your-business",
        "terms_url": "https://www.sba.gov/about-sba/open-government/about-sbagov-website/linking-policy",
        "license": "U.S. federal public source with SBA acknowledgement requested; SBA website disclaimer and linking policy apply",
        "license_version": "current SBA.gov website posture",
        "authority_tier": "official_government",
        "domain": "business_entrepreneurship",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly SBA guide and terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the U.S. Small Business Administration.",
    },
    {
        "source_id": "nps.recreation-safety",
        "source_name": "National Park Service Health & Safety public reference page",
        "publisher": "National Park Service",
        "source_url": "https://www.nps.gov/subjects/healthandsafety/index.htm",
        "terms_url": "https://www.nps.gov/aboutus/disclaimer.htm",
        "license": "U.S. federal public website text with NPS disclaimer, third-party, trademark, and media caveats retained",
        "license_version": "current NPS.gov disclaimer posture",
        "authority_tier": "official_government",
        "domain": "hobbies_recreation",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly NPS health and safety page and disclaimer re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the National Park Service.",
    },
    {
        "source_id": "americorps.volunteer_rate_state",
        "source_name": "AmeriCorps Open Data State Ranking by Volunteer Rate",
        "publisher": "AmeriCorps / Corporation for National and Community Service",
        "source_url": "https://data.americorps.gov/National-Service/State-Ranking-by-Volunteer-Rate/qbmh-b8k5",
        "terms_url": "https://data.americorps.gov/National-Service/State-Ranking-by-Volunteer-Rate/qbmh-b8k5",
        "license": "AmeriCorps Open Data Socrata metadata licenseId PUBLIC_DOMAIN; public-domain dataset metadata and public statistical reference data only",
        "license_version": "Socrata dataset metadata licenseId PUBLIC_DOMAIN reviewed 2026-06-28",
        "authority_tier": "official_government",
        "domain": "volunteering_public_reference",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "fixture tests offline; live Socrata metadata/data access requires --live/--execute and small public dataset budget policy",
        "freshness_cadence": "biennial dataset posting context with quarterly metadata and license re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from AmeriCorps Open Data.",
    },
    {
        "source_id": "cdc.physical-activity.basics",
        "source_name": "CDC Physical Activity Basics public reference pages",
        "publisher": "Centers for Disease Control and Prevention",
        "source_url": "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
        "terms_url": "https://www.cdc.gov/other/agencymaterials.html",
        "license": "U.S. federal public website text with CDC attribution, no-endorsement, third-party, trademark, and media caveats retained",
        "license_version": "current CDC.gov reuse posture",
        "authority_tier": "official_government",
        "domain": "health_wellness_reference",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly CDC physical activity page and reuse terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Centers for Disease Control and Prevention.",
    },
    {
        "source_id": "official.statcan.table.13100974",
        "source_name": "Statistics Canada Table 13-10-0974-01",
        "publisher": "Government of Canada, Statistics Canada",
        "source_url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310097401",
        "terms_url": "https://www.statcan.gc.ca/en/terms-conditions/open-licence",
        "license": "Statistics Canada Open Licence with source acknowledgement, no-endorsement, no-misrepresentation, no-reidentification, and third-party rights caveats retained",
        "license_version": "current Statistics Canada open licence posture reviewed 2026-06-28",
        "authority_tier": "official_government",
        "domain": "health_wellness_reference",
        "jurisdiction": "CA",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live static HTTPS downloads require --live, --execute, and static download budget policy",
        "freshness_cadence": "quarterly Statistics Canada table and open licence re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from Statistics Canada Table 13-10-0974-01.",
    },
    {
        "source_id": "state.travel.public_travel",
        "source_name": "Travel.State.Gov passport and travel advisory public reference pages",
        "publisher": "U.S. Department of State",
        "source_url": "https://travel.state.gov/content/travel/en/passports/how-apply.html",
        "terms_url": "https://travel.state.gov/content/travel/en/copyright-disclaimer.html",
        "license": "U.S. federal public website text with State Department copyright, third-party, trademark, and media caveats retained",
        "license_version": "current Travel.State.Gov copyright and disclaimer posture",
        "authority_tier": "official_government",
        "domain": "travel_relocation",
        "jurisdiction": "US and destination-specific",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly State travel pages and terms re-review; advisory freshness requires strict official-source recheck before critical use",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from Travel.State.Gov, U.S. Department of State.",
    },
    {
        "source_id": "usa.gov.change_address",
        "source_name": "USA.gov change-address public relocation reference page",
        "publisher": "USA.gov / General Services Administration",
        "source_url": "https://www.usa.gov/change-address",
        "terms_url": "https://www.usa.gov/government-works",
        "license": "U.S. federal public website text with USA.gov government-works, third-party, trademark, and media caveats retained",
        "license_version": "current USA.gov government works posture",
        "authority_tier": "official_government",
        "domain": "travel_relocation",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly USA.gov change-address page and government-works terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from USA.gov.",
    },
    {
        "source_id": "irs.when_to_file",
        "source_name": "IRS When to File individual return public reference page",
        "publisher": "Internal Revenue Service",
        "source_url": "https://www.irs.gov/filing/individuals/when-to-file",
        "terms_url": "https://www.irs.gov/privacy-disclosure/irs-privacy-policy",
        "license": "U.S. federal public website text with IRS privacy, disclosure, third-party, trademark, and media caveats retained",
        "license_version": "current IRS.gov public website posture",
        "authority_tier": "regulated_body",
        "domain": "finance_public_reference",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly IRS filing page and policy re-review; tax deadline references require strict official-source recheck before critical use",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Internal Revenue Service.",
    },
    {
        "source_id": "cfpb.adult_financial_education",
        "source_name": "CFPB adult financial education tools and resources",
        "publisher": "Consumer Financial Protection Bureau",
        "source_url": "https://www.consumerfinance.gov/consumer-tools/educator-tools/adult-financial-education/tools-and-resources/",
        "terms_url": "https://www.consumerfinance.gov/privacy/",
        "license": "U.S. federal public website text with CFPB privacy, third-party, trademark, and media caveats retained",
        "license_version": "current ConsumerFinance.gov public website posture",
        "authority_tier": "regulated_body",
        "domain": "finance_public_reference",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly CFPB education page and privacy/terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Consumer Financial Protection Bureau.",
    },
    {
        "source_id": "usa.gov.benefits",
        "source_name": "USA.gov government benefits public reference page",
        "publisher": "USA.gov / General Services Administration",
        "source_url": "https://www.usa.gov/benefits",
        "terms_url": "https://www.usa.gov/government-works",
        "license": "U.S. federal public website text with USA.gov government-works, third-party, trademark, and media caveats retained",
        "license_version": "current USA.gov government works posture",
        "authority_tier": "official_government",
        "domain": "finance_public_reference",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly USA.gov benefits page and government-works terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from USA.gov.",
    },
    {
        "source_id": "ready.gov.kit",
        "source_name": "Ready.gov Build A Kit public preparedness reference page",
        "publisher": "Ready.gov / Federal Emergency Management Agency",
        "source_url": "https://www.ready.gov/kit",
        "terms_url": "https://www.ready.gov/terms-and-conditions",
        "license": "U.S. federal public website text with Ready.gov terms, third-party, trademark, and media caveats retained",
        "license_version": "current Ready.gov terms and conditions posture",
        "authority_tier": "official_government",
        "domain": "home_life_admin",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly Ready.gov kit page and terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from Ready.gov.",
    },
    {
        "source_id": "energy.gov.energy_saver",
        "source_name": "Department of Energy Energy Saver public home energy reference pages",
        "publisher": "U.S. Department of Energy",
        "source_url": "https://www.energy.gov/energysaver/energy-saver",
        "terms_url": "https://www.energy.gov/web-policies",
        "license": "U.S. federal public website government information with DOE acknowledgement requested and third-party, trademark, and media caveats retained",
        "license_version": "current Energy.gov web-policies posture",
        "authority_tier": "official_government",
        "domain": "home_life_admin",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly DOE Energy Saver page and web-policies re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the U.S. Department of Energy.",
    },
    {
        "source_id": "usa.gov.home_repair",
        "source_name": "USA.gov government home repair assistance public reference page",
        "publisher": "USA.gov / General Services Administration",
        "source_url": "https://www.usa.gov/home-repair-programs",
        "terms_url": "https://www.usa.gov/government-works",
        "license": "U.S. federal public website text with USA.gov government-works, third-party, trademark, and media caveats retained",
        "license_version": "current USA.gov government works posture",
        "authority_tier": "official_government",
        "domain": "home_life_admin",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly USA.gov home repair page and government-works terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from USA.gov.",
    },
    {
        "source_id": "creative-commons.licenses",
        "source_name": "Creative Commons licenses and public-domain tools public reference page",
        "publisher": "Creative Commons",
        "source_url": "https://creativecommons.org/licenses/",
        "terms_url": "https://creativecommons.org/terms/",
        "license": "Creative Commons website content CC BY 4.0 unless otherwise marked; legal tools, deeds, and notices identified as CC0, with trademark and third-party caveats retained",
        "license_version": "current Creative Commons website terms and policies posture",
        "authority_tier": "official_institution",
        "domain": "creative_project_reference",
        "jurisdiction": "global",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly Creative Commons licenses, terms, and policies re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from Creative Commons.",
    },
    {
        "source_id": "w3c.web-standards",
        "source_name": "W3C web standards public reference page",
        "publisher": "World Wide Web Consortium",
        "source_url": "https://www.w3.org/standards/",
        "terms_url": "https://www.w3.org/copyright/",
        "license": "W3C public standards and website reference posture with document, software, test-suite, patent-policy, trademark, and permission caveats retained",
        "license_version": "current W3C copyright and policies posture",
        "authority_tier": "standards_body",
        "domain": "creative_project_reference",
        "jurisdiction": "global",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly W3C standards page, copyright, and policy re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the World Wide Web Consortium.",
    },
    {
        "source_id": "loc.primary_sources",
        "source_name": "Library of Congress Getting Started with Primary Sources public learning reference page",
        "publisher": "Library of Congress",
        "source_url": "https://www.loc.gov/programs/teachers/getting-started-with-primary-sources/",
        "terms_url": "https://www.loc.gov/legal/",
        "license": "Library of Congress page text marked U.S. Government Work; collection items, third-party material, media, and rights-restricted content excluded",
        "license_version": "current LOC legal and page-level rights posture",
        "authority_tier": "official_government",
        "domain": "creative_project_reference",
        "jurisdiction": "US federal",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly Library of Congress primary sources page and legal/rights re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Library of Congress.",
    },
    {
        "source_id": "nih.medlineplus.wellness",
        "source_name": "MedlinePlus wellness and lifestyle health topic summaries",
        "publisher": "National Library of Medicine / National Institutes of Health",
        "source_url": "https://medlineplus.gov/",
        "terms_url": "https://medlineplus.gov/about/using/usingcontent/",
        "license": "MedlinePlus health topic summaries are public-domain federal content with acknowledgement requested; copyrighted vendor drug, supplement, encyclopedia, image, and third-party content excluded",
        "license_version": "current MedlinePlus content reuse posture",
        "authority_tier": "official_institution",
        "domain": "personal_growth",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly MedlinePlus wellness topic and content-use terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from MedlinePlus, National Library of Medicine.",
    },
    {
        "source_id": "openalex.personal_growth_research",
        "source_name": "OpenAlex personal-growth scholarly metadata reference",
        "publisher": "OpenAlex",
        "source_url": "https://openalex.org/",
        "terms_url": "https://docs.openalex.org/download-all-data/openalex-snapshot",
        "license": "OpenAlex CC0 public scholarly metadata with high-volume API/snapshot governance retained",
        "license_version": "current OpenAlex CC0 metadata posture",
        "authority_tier": "scholarly_metadata",
        "domain": "personal_growth",
        "jurisdiction": "global",
        "language": "en",
        "attribution_required": False,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": "optional for low-budget live API; required for high-volume use",
        "rate_limit_policy": "fixture tests offline; live API requires --live, rate/budget policy, and high-volume approval for bulk use",
        "freshness_cadence": "monthly OpenAlex metadata and API-governance review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public scholarly metadata from OpenAlex.",
    },
    {
        "source_id": "cdc.positive_parenting",
        "source_name": "CDC Positive Parenting Tips public reference pages",
        "publisher": "Centers for Disease Control and Prevention",
        "source_url": "https://www.cdc.gov/child-development/positive-parenting-tips/index.html",
        "terms_url": "https://www.cdc.gov/other/agencymaterials.html",
        "license": "U.S. federal public website text with CDC attribution, no-endorsement, third-party, trademark, and media caveats retained",
        "license_version": "current CDC.gov reuse posture",
        "authority_tier": "official_government",
        "domain": "relationships_family",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly CDC positive parenting page and reuse terms re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Centers for Disease Control and Prevention.",
    },
    {
        "source_id": "acf.healthy_marriage_fatherhood",
        "source_name": "ACF Healthy Marriage and Responsible Fatherhood public reference pages",
        "publisher": "Administration for Children and Families",
        "source_url": "https://acf.gov/ofa/programs/healthy-marriage",
        "terms_url": "https://acf.gov/digital-policies",
        "license": "U.S. federal public website text with ACF/HHS digital policy, third-party, trademark, and media caveats retained",
        "license_version": "current ACF.gov digital policy posture",
        "authority_tier": "official_government",
        "domain": "relationships_family",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy; current environment may receive ACF WAF challenge",
        "freshness_cadence": "quarterly ACF HMRF page and digital policy re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from the Administration for Children and Families.",
    },
    {
        "source_id": "childwelfare.family_support",
        "source_name": "Child Welfare Information Gateway family support public reference resources",
        "publisher": "Child Welfare Information Gateway / Children's Bureau / Administration for Children and Families",
        "source_url": "https://www.childwelfare.gov/resources/",
        "terms_url": "https://www.childwelfare.gov/information-gateway-policies/",
        "license": "Official Child Welfare Information Gateway public website/publication posture with ACF/HHS attribution, third-party, trademark, and media caveats retained",
        "license_version": "current ChildWelfare.gov information gateway policies posture",
        "authority_tier": "official_institution",
        "domain": "relationships_family",
        "jurisdiction": "US",
        "language": "en",
        "attribution_required": True,
        "redistribution_policy": DistributionPolicy.REDISTRIBUTABLE_WITH_ATTRIBUTION.value,
        "r2_pack_policy": R2PackPolicy.R2_PACK_ALLOWED.value,
        "derivatives_allowed": True,
        "api_key_required": False,
        "rate_limit_policy": "static fixture tests offline; live page checks require --live and static page budget policy",
        "freshness_cadence": "quarterly ChildWelfare.gov resources and information gateway policies re-review",
        "last_terms_reviewed": "2026-06-28",
        "terms_review_status": "reviewed",
        "allowed_artifact_classes": PUBLIC_PACK_CLASSES,
        "forbidden_artifact_classes": FORBIDDEN_ARTIFACT_CLASS_GROUPS,
        "review_required": False,
        "attribution_text": "Based on public reference data from Child Welfare Information Gateway.",
    },
]


def terms_registry_artifact() -> dict[str, Any]:
    return {
        "schemaVersion": 1,
        "kind": "ambitions.sourceAtlas.termsRegistry.v1",
        "versionID": TERMS_REGISTRY_VERSION,
        "dataClass": "official_public_source",
        "createdAt": utc_now(),
        "privacyBoundary": PRIVACY_BOUNDARY,
        "sources": SOURCE_TERMS_REGISTRY,
    }


def terms_entry(source_id: str) -> dict[str, Any]:
    lookup = {entry["source_id"]: entry for entry in SOURCE_TERMS_REGISTRY}
    if source_id not in lookup:
        raise KeyError(f"unknown terms registry source_id: {source_id}")
    return lookup[source_id]


def validate_terms_registry() -> dict[str, Any]:
    issues: list[str] = []
    required = [
        "source_id",
        "source_name",
        "publisher",
        "source_url",
        "terms_url",
        "license",
        "license_version",
        "authority_tier",
        "domain",
        "jurisdiction",
        "language",
        "attribution_required",
        "redistribution_policy",
        "r2_pack_policy",
        "derivatives_allowed",
        "api_key_required",
        "rate_limit_policy",
        "freshness_cadence",
        "last_terms_reviewed",
        "terms_review_status",
        "allowed_artifact_classes",
        "forbidden_artifact_classes",
        "review_required",
    ]
    seen: set[str] = set()
    for entry in SOURCE_TERMS_REGISTRY:
        source_id = entry.get("source_id", "<unknown>")
        if source_id in seen:
            issues.append(f"{source_id}: duplicate source_id")
        seen.add(source_id)
        for field in required:
            value = entry.get(field)
            if field not in entry or value is None or value == "" or value == []:
                issues.append(f"{source_id}: missing {field}")
        if entry.get("redistribution_policy") not in {item.value for item in DistributionPolicy}:
            issues.append(f"{source_id}: unsupported redistribution_policy")
        if entry.get("r2_pack_policy") not in {item.value for item in R2PackPolicy}:
            issues.append(f"{source_id}: unsupported r2_pack_policy")
    return {
        "valid": not issues,
        "issueCount": len(issues),
        "issues": issues,
        "sourceCount": len(SOURCE_TERMS_REGISTRY),
    }


def policy_gate_for_output(
    source_id: str,
    output: dict[str, Any],
    review_evidence: dict[str, Any] | None = None,
    *,
    require_approval_packet: bool = False,
) -> dict[str, Any]:
    return validate_distribution_policy(
        terms_entry(source_id),
        output,
        review_evidence,
        require_approval_packet=require_approval_packet,
    )
