#!/usr/bin/env python3
"""Generate a fast Ambitions batch closeout report skeleton from current repo state.

This is documentation automation only. It does not validate the batch or prove readiness.
"""
from __future__ import annotations

import argparse
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(cmd: list[str]) -> tuple[int, str, str]:
    proc = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return proc.returncode, proc.stdout, proc.stderr


def git_changed() -> list[str]:
    code, stdout, _ = run(["git", "status", "--porcelain"])
    if code != 0:
        return []
    paths: list[str] = []
    for line in stdout.splitlines():
        if len(line) >= 4:
            path = line[3:].strip()
            if " -> " in path:
                path = path.split(" -> ", 1)[1]
            paths.append(path)
    return sorted(paths)


def report_path(batch_id: str) -> Path:
    slug = batch_id.lower().replace("_", "-")
    return ROOT / "docs/audits" / f"{slug}-batch-closeout-report.md"


def build_report(batch_id: str, status: str, hbi: str, mri: str, validation: list[str]) -> str:
    changed = git_changed()
    changed_text = "\n".join(f"- `{path}`" for path in changed) if changed else "- None detected at generation time."
    validation_text = "\n".join(f"- `{cmd}`" for cmd in validation) if validation else "- Not recorded by accelerator. Replace with actual commands and exit codes."
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    return f"""# {batch_id} Batch Closeout Report

Status: {status}  
Generated: {now}  
Generated by: `scripts/ambitions-batch-closeout-accelerator.py`

## Scope

Batch: `{batch_id}`

## HBI applicability

{hbi}

## MRI applicability

{mri}

## Files changed at generation time

{changed_text}

## Validation commands and exit codes

{validation_text}

## Claims made

- Batch-local claims only if backed by the final implementation and validation evidence.

## Claims not made

- No release readiness claim.
- No device proof claim unless device proof is attached.
- No TestFlight/App Store claim.
- No accessibility compliance claim unless audited evidence is attached.
- No privacy/legal approval claim unless active proof is attached.

## Yellow / Red notes

Replace with actual outcome. Do not convert non-Green results into Green.

## Rollback notes

Revert only batch-owned files unless a broader revert is proven necessary.

## Next eligible batch

Resolve from repo truth after this batch closes.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Create/update a batch closeout report skeleton quickly.")
    parser.add_argument("--batch", required=True)
    parser.add_argument("--status", default="Draft")
    parser.add_argument("--hbi", default="Not classified")
    parser.add_argument("--mri", default="Not classified")
    parser.add_argument("--validation", action="append", default=[])
    parser.add_argument("--print-path", action="store_true")
    args = parser.parse_args()

    path = report_path(args.batch)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_report(args.batch, args.status, args.hbi, args.mri, args.validation), encoding="utf-8")
    if args.print_path:
        print(path.relative_to(ROOT))
    else:
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
