#!/usr/bin/env python3
"""Generate human-readable VSP provenance handoff documents."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROVENANCE_DIR = ROOT / "docs" / "design" / "provenance"

REGISTRY_PATHS = {
    "vsp": PROVENANCE_DIR / "vsp-provenance.json",
    "components": PROVENANCE_DIR / "component-registry.json",
    "nodes": PROVENANCE_DIR / "figma-node-index.json",
    "proofs": PROVENANCE_DIR / "proof-registry.json",
    "linear": PROVENANCE_DIR / "linear-map.json",
}

OUTPUTS = {
    "map": PROVENANCE_DIR / "VSP-SwiftUI-Provenance-Map.md",
    "gallery": PROVENANCE_DIR / "Component-Gallery.md",
    "gaps": PROVENANCE_DIR / "Gap-Register.md",
    "figma": PROVENANCE_DIR / "Figma-Annotation-Pack.md",
    "linear": PROVENANCE_DIR / "Linear-Issue-Pack.md",
    "gates": PROVENANCE_DIR / "Governance-Gates.md",
}

PROOF_LABELS = {
    "owner_approval": "owner approval",
    "live_swiftui_screenshot": "live SwiftUI screenshot",
    "device_screenshot": "device screenshot",
    "dynamic_type": "Dynamic Type",
    "voiceover": "VoiceOver",
    "reduce_motion": "Reduce Motion",
    "increase_contrast": "Increase Contrast",
    "reduce_transparency": "Reduce Transparency",
    "haptics": "haptics",
    "runtime_behavior": "runtime behavior",
    "validation_commands": "validation commands",
    "privacy_boundary": "privacy boundary",
}


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def rel(path: str | Path) -> str:
    path = Path(path)
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def link(path: str) -> str:
    return f"[{path}]({path})"


def bullet_list(items: list[str]) -> str:
    if not items:
        return "- none recorded\n"
    return "".join(f"- {item}\n" for item in items)


def inline_list(items: list[str], empty: str = "none recorded") -> str:
    if not items:
        return empty
    return "<br>".join(items)


def vsp_sort_key(vsp: dict[str, Any]) -> int:
    return int(vsp["vsp_id"].split("-")[1])


def get_vsp_packets(registry: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(registry["vsp_packets"], key=vsp_sort_key)


def proof_entries_for(proofs: list[dict[str, Any]], vsp_id: str) -> list[dict[str, Any]]:
    return [proof for proof in proofs if proof["vsp_id"] == vsp_id]


def missing_required_proofs(vsp: dict[str, Any], proofs: list[dict[str, Any]]) -> list[str]:
    present_by_type = {
        proof["proof_type"]: proof
        for proof in proof_entries_for(proofs, vsp["vsp_id"])
    }
    missing: list[str] = []
    for key, required in vsp["proof_required"].items():
        if not required:
            continue
        proof_type = key_to_proof_type(key)
        proof = present_by_type.get(proof_type)
        if proof is None or proof["status"] != "present":
            missing.append(PROOF_LABELS.get(key, key))
    return missing


def key_to_proof_type(key: str) -> str:
    mapping = {
        "owner_approval": "owner_approval",
        "live_swiftui_screenshot": "swiftui_simulator_screenshot",
        "device_screenshot": "swiftui_device_screenshot",
        "dynamic_type": "dynamic_type_screenshot",
        "voiceover": "voiceover_manual_note",
        "reduce_motion": "reduce_motion_walkthrough",
        "increase_contrast": "increase_contrast_check",
        "reduce_transparency": "reduce_transparency_check",
        "haptics": "haptic_device_note",
        "runtime_behavior": "runtime_behavior_test",
        "validation_commands": "validation_command",
        "privacy_boundary": "privacy_boundary_check",
    }
    return mapping[key]


def docs_header(title: str) -> str:
    return (
        f"# {title}\n\n"
        "Generated by `scripts/ambitions-provenance-report-generate.py` from current registry inputs.\n\n"
        "Claim boundary: this document is a Git-owned provenance/handoff artifact. "
        "It is not Code Connect, not Visual Green, not source implementation, not device proof, "
        "not accessibility conformance, and not owner approval.\n\n"
    )


def generate_map(vsps: list[dict[str, Any]], proofs: list[dict[str, Any]]) -> str:
    lines = [docs_header("VSP SwiftUI Provenance Map")]
    lines.append("## Executive Summary\n\n")
    lines.append(
        "VSP-01 is the immutable approved shell authority. VSP-02 through VSP-10 are Yellow "
        "candidate/content/proof/anatomy layers that must remain content-only or mount inside "
        "the exact VSP-01 shell. Git provenance is canonical for implementation ownership; "
        "Linear and Figma annotations mirror this registry.\n\n"
    )
    lines.append("## Shell Authority\n\n")
    lines.append(
        "- VSP-01 owns root shell/chrome authority.\n"
        "- VSP-02 through VSP-10 must require VSP-01 and may not mutate shell.\n"
        "- No packet may introduce Capture as a tab, Motion as a destination, or Trust details as root surfaces.\n\n"
    )
    lines.append("## VSP Table\n\n")
    lines.append("| VSP | Title | Category | Figma Evidence | Source Owner | Allowed Paths | Forbidden Paths | Linear Mirror | Ceiling | Missing Proof | Next Allowed Action |\n")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|\n")
    for vsp in vsps:
        figma = vsp["figma"]
        swiftui = vsp["swiftui"]
        missing = missing_required_proofs(vsp, proofs)
        evidence = figma["screenshot_paths"] + figma["evidence_paths"]
        lines.append(
            "| {id} | {title} | {category} | {figma_evidence} | {owners} | {allowed} | {forbidden} | {linear} | {ceiling} | {missing} | {action} |\n".format(
                id=vsp["vsp_id"],
                title=vsp["title"],
                category=vsp["category"],
                figma_evidence=inline_list(evidence),
                owners=inline_list(swiftui["canonical_source_owners"]),
                allowed=inline_list(swiftui["allowed_implementation_areas"]),
                forbidden=inline_list(swiftui["forbidden_implementation_areas"]),
                linear=vsp["linear"]["likely_parent_issue"],
                ceiling=vsp["proof_ceiling"],
                missing=inline_list(missing),
                action=vsp["current_status_recommendation"],
            )
        )
    lines.append("\n## Hard Go / No-Go\n\n")
    lines.append("| Gate | Decision |\n|---|---|\n")
    lines.append("| VSP-01 shell parity absent | No VSP-02 through VSP-08 source implementation without a shell-parity leaf. |\n")
    lines.append("| VSP-10 source map absent | No Codex implementation ownership guessing. |\n")
    lines.append("| VSP-09 accessibility/motion matrix absent | No visual-polish or motion claims beyond Yellow. |\n")
    lines.append("| Missing Figma node or screenshot | No Visual Green. |\n")
    lines.append("| Missing owner approval | No Done, no Visual Green. |\n\n")
    lines.append("## Green Requirements\n\n")
    lines.append(
        "- explicit owner approval tied to frame IDs and screenshot proof;\n"
        "- live SwiftUI render proof tied to current source and SHA;\n"
        "- accessibility proof for Dynamic Type, VoiceOver, Reduce Motion, Reduce Transparency, Increase Contrast, and haptics where relevant;\n"
        "- validation command proof;\n"
        "- VSP-08 privacy/offline/account/R2 boundary proof;\n"
        "- no product-law or shell-authority violation.\n\n"
    )
    lines.append("## Rejected Interpretations\n\n")
    lines.append(
        "- Capture as tab, inbox, chatbot, root destination, or persistent floating button.\n"
        "- Motion as tab, root destination, analytics feed, score, streak, or dashboard.\n"
        "- Proof, Source, Privacy, History, or Receipts as root surfaces.\n"
        "- Plan, Profile, Habits, or Insights as top-level IA.\n"
        "- Figma candidate screenshot or source existence as Green proof.\n"
    )
    return "".join(lines)


def generate_gallery(vsps: list[dict[str, Any]], components: list[dict[str, Any]]) -> str:
    lines = [docs_header("Component Gallery")]
    lines.append(
        "This is a non-rendering gallery for slow or unavailable Xcode Preview contexts. "
        "It lists source owners and candidate Figma screenshots; it does not fake SwiftUI renders.\n\n"
    )
    for vsp in vsps:
        group = [component for component in components if vsp["vsp_id"] in component["owning_vsp_ids"]]
        lines.append(f"## {vsp['vsp_id']} - {vsp['title']}\n\n")
        lines.append("Figma candidate screenshots:\n")
        lines.append(bullet_list(vsp["figma"]["screenshot_paths"]))
        lines.append("SwiftUI source owners:\n")
        lines.append(bullet_list(vsp["swiftui"]["canonical_source_owners"]))
        lines.append("Candidate components:\n")
        for component in group:
            lines.append(f"- `{component['component_name']}` (`{component['component_kind']}`) - `{component['source_path']}` - proof: `{component['proof_status']}`\n")
        if not group:
            lines.append("- none mapped\n")
        lines.append("Known previews/tests/quality files:\n")
        known = vsp["swiftui"]["known_tests"] + vsp["swiftui"]["known_preview_or_quality_files"]
        lines.append(bullet_list(known))
        lines.append("Current visual proof status: SwiftUI render missing unless listed as a current live screenshot in the proof registry.\n\n")
        lines.append("Required later for Green: live render, screenshot matrix, accessibility matrix, owner approval, and validation logs tied to current source.\n\n")
    return "".join(lines)


def generate_gaps(vsps: list[dict[str, Any]], proofs: list[dict[str, Any]]) -> str:
    lines = [docs_header("Gap Register")]
    lines.append("| Gap ID | Group | Affected VSPs | Severity | Reason | Recommended Owner | Recommended Linear Status | Required Proof To Close | Blocks |\n")
    lines.append("|---|---|---|---|---|---|---|---|---|\n")
    gap_id = 1

    groups = [
        ("Figma node gaps", "Medium", "Any unknown or unreviewed node must be resolved before Visual Green.", "Design systems / Figma"),
        ("source-owner gaps", "High", "No source owner means Codex would guess implementation ownership.", "VSP-10 source anatomy"),
        ("proof gaps", "High", "Owner, render, device, and validation evidence are missing or incomplete.", "QA / implementation leaf owner"),
        ("accessibility gaps", "High", "Dynamic Type, VoiceOver, Reduce Motion, Reduce Transparency, Increase Contrast, and haptics are not fully proven.", "VSP-09 accessibility owner"),
        ("motion/haptics gaps", "Medium", "Motion/haptic acceptance is policy-mapped but not device-proven.", "Interaction / Stage Motion"),
        ("privacy/external-boundary gaps", "High", "Account/R2/Source Atlas/offline boundaries require proof before VSP-08 can advance.", "Privacy / Source Atlas"),
        ("stale vocabulary gaps", "Medium", "Plan/Profile/Habits/Insights can appear only as stale risks or rejected interpretations, not root IA.", "Language / provenance audit"),
        ("Linear/workflow gaps", "Low", "Linear is a mirror and must not be mutated by this task.", "Project operations"),
        ("validation-script gaps", "Medium", "Generated inventories and audits are local checks, not render/device proof.", "QA / Codex"),
    ]
    for group, severity, reason, owner in groups:
        affected = [vsp["vsp_id"] for vsp in vsps]
        if group == "privacy/external-boundary gaps":
            affected = ["VSP-08"]
        if group == "motion/haptics gaps":
            affected = ["VSP-09"]
        if group == "source-owner gaps":
            affected = ["VSP-10"]
        if group == "Figma node gaps":
            affected = [vsp["vsp_id"] for vsp in vsps if vsp["figma"]["node_id_status"] != "known"]
        if not affected:
            affected = ["none currently"]
        proof = "Owner-approved proof artifacts, current screenshots, accessibility notes, and validation output as applicable."
        blocks = "implementation" if severity == "High" else "Green only"
        lines.append(
            f"| GAP-{gap_id:03d} | {group} | {', '.join(affected)} | {severity} | {reason} | {owner} | Needs Repair | {proof} | {blocks} |\n"
        )
        gap_id += 1

    lines.append("\n## VSP-Specific Missing Evidence\n\n")
    for vsp in vsps:
        missing = sorted(set(vsp["missing_evidence"] + missing_required_proofs(vsp, proofs)))
        lines.append(f"### {vsp['vsp_id']} - {vsp['title']}\n\n")
        lines.append(bullet_list(missing))
    return "".join(lines)


def generate_figma_pack(vsps: list[dict[str, Any]]) -> str:
    lines = [docs_header("Figma Annotation Pack")]
    lines.append("These blocks are generated copy for manual Figma annotations. They are not confirmed in Figma.\n\n")
    for vsp in vsps:
        figma = vsp["figma"]
        swiftui = vsp["swiftui"]
        missing = ", ".join(vsp["missing_evidence"]) or "none recorded"
        lines.append(f"## {vsp['vsp_id']} - {vsp['title']}\n\n")
        lines.append("```text\n")
        lines.append(f"Annotation title: {vsp['vsp_id']} provenance - {vsp['title']}\n")
        lines.append(f"Frame naming recommendation: {figma['frame_name']}\n")
        lines.append(f"Shell relationship: requires VSP-01 shell = {vsp['shell_authority']['requires_vsp_01_shell']}; may mutate shell = {vsp['shell_authority']['may_mutate_shell']}\n")
        lines.append(f"SwiftUI source owner: {', '.join(swiftui['canonical_source_owners']) or 'blocking gap'}\n")
        lines.append(f"Allowed implementation area: {', '.join(swiftui['allowed_implementation_areas'])}\n")
        lines.append(f"Forbidden implementation area: {', '.join(swiftui['forbidden_implementation_areas'])}\n")
        lines.append(f"Proof ceiling: {vsp['proof_ceiling']}\n")
        lines.append(f"Missing proof: {missing}\n")
        lines.append(f"Linear mirror: {vsp['linear']['likely_parent_issue']} ({vsp['linear']['recommended_status']})\n")
        lines.append("Non-claim: this annotation is not Code Connect, not Visual Green, not source implementation, and not owner approval.\n")
        lines.append("```\n\n")
    return "".join(lines)


def generate_linear_pack(linear_items: list[dict[str, Any]]) -> str:
    lines = [docs_header("Linear Issue Pack")]
    lines.append("Do not create or update Linear from this generated pack without explicit owner authorization.\n\n")
    lines.append("Recommended hierarchy: Initiative -> Project/Epic -> Milestone -> Parent Issue/Feature -> Sub-issue/Codex leaf.\n\n")
    lines.append("Recommended project/epic title: VSP North Star Figma Authority and SwiftUI Provenance Handoff.\n\n")
    for item in sorted(linear_items, key=lambda row: int(row["vsp_id"].split("-")[1])):
        lines.append(f"## {item['vsp_id']} - {item['recommended_parent_title']}\n\n")
        lines.append(f"- Parent issue mirror: `{item['likely_parent_issue']}`\n")
        lines.append(f"- Recommended status: `{item['recommended_status']}`\n")
        lines.append(f"- Labels: {', '.join(item['recommended_labels'])}\n")
        lines.append(f"- Blocked by: {', '.join(item['blocked_by']) or 'none recorded'}\n")
        lines.append(f"- Do not create now: `{item['do_not_create_now']}`\n\n")
        lines.append("Acceptance summary:\n")
        lines.append(bullet_list(item["acceptance_summary"]))
        lines.append("Validation summary:\n")
        lines.append(bullet_list(item["validation_summary"]))
        lines.append("Recommended sub-issues:\n")
        for sub in item["recommended_sub_issues"]:
            lines.append(f"- {sub['title']} - scope: {sub['scope']} - status: {sub['recommended_status']}\n")
        lines.append("\nStandard Codex closeout block:\n\n")
        lines.append("```text\nStatus:\nScope completed:\nFiles changed:\nProduct law preserved:\nValidation run:\nValidation not run:\nProof artifacts:\nKnown risks:\nFollow-up required:\nRollback plan:\n```\n\n")
    return "".join(lines)


def generate_gates() -> str:
    lines = [docs_header("Governance Gates")]
    lines.append("## Yellow vs Green\n\n")
    lines.append(
        "Yellow means the registry has candidate evidence, source-owner mapping, or proof scaffolding, "
        "but one or more owner/render/device/accessibility/privacy/validation requirements are missing. "
        "Green requires current proof and owner approval for the exact scope.\n\n"
    )
    lines.append("## Hard Gates\n\n")
    gates = [
        "No Green without current proof.",
        "No source owner, no implementation.",
        "No Figma node, no Visual Green.",
        "No durable screenshot, no Visual Green.",
        "No accessibility proof, no Green.",
        "No private-egress proof, no VSP-08 Green.",
        "No shell parity, no VSP-02 through VSP-08 implementation.",
        "No VSP-10 source map, no implementation.",
        "No VSP-09 proof matrix, no visual-polish or motion Green.",
        "VSP-02 through VSP-10 may not mutate VSP-01 shell.",
        "Capture must remain global composer, Motion behavior, Trust inspection, and R2 public/reference only.",
    ]
    lines.append(bullet_list(gates))
    lines.append("\n## Allowed Implementation States\n\n")
    lines.append(
        "- Designing: Figma or registry repair active, no source implementation.\n"
        "- Spec Ready: owner-approved Figma frame and source-owner map exist, but Codex leaf not started.\n"
        "- Ready For Codex: implementation leaf has accepted scope, non-goals, validation, and proof artifacts.\n"
        "- Ready For Review: current implementation proof exists and owner review remains.\n"
        "- Accepted Yellow: owner explicitly accepts a named risk and follow-up; never Green.\n\n"
    )
    lines.append("## Validation Commands\n\n")
    lines.append("```bash\n")
    lines.append("python3 scripts/ambitions-component-inventory-generate.py\n")
    lines.append("python3 scripts/ambitions-provenance-report-generate.py\n")
    lines.append("python3 scripts/ambitions-vsp-provenance-audit.py\n")
    lines.append("git diff --check\n")
    lines.append("```\n")
    return "".join(lines)


def main() -> int:
    registries = {name: load_json(path) for name, path in REGISTRY_PATHS.items()}
    vsps = get_vsp_packets(registries["vsp"])
    components = registries["components"]["components"]
    proofs = registries["proofs"]["proofs"]
    linear_items = registries["linear"]["linear_items"]

    OUTPUTS["map"].write_text(generate_map(vsps, proofs).rstrip() + "\n", encoding="utf-8")
    OUTPUTS["gallery"].write_text(generate_gallery(vsps, components).rstrip() + "\n", encoding="utf-8")
    OUTPUTS["gaps"].write_text(generate_gaps(vsps, proofs).rstrip() + "\n", encoding="utf-8")
    OUTPUTS["figma"].write_text(generate_figma_pack(vsps).rstrip() + "\n", encoding="utf-8")
    OUTPUTS["linear"].write_text(generate_linear_pack(linear_items).rstrip() + "\n", encoding="utf-8")
    OUTPUTS["gates"].write_text(generate_gates().rstrip() + "\n", encoding="utf-8")

    for label, path in OUTPUTS.items():
        print(f"Wrote {rel(path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
