#!/usr/bin/env python3
from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any
import json

from ambitions_frontend_authority_common import (
    BATCH_ID,
    REPORT_DIR,
    SOURCE_BINDINGS_PATH,
    combined_surface_payload,
    dedupe,
    proof_binding_status,
    surface_counts_by,
    universe_rows,
    write_json,
    write_json_like_yaml,
    write_text,
)
from ambitions_signature_visual_instruments import enrich_packet_with_instrument, instrument_counts, missing_top_level_instruments


def generated_swift_case_name(surface_id: str) -> str:
    return surface_id


def generated_destination_case_name(destination: str) -> str:
    return destination.lower().replace(" ", "_").replace("-", "_")


def unique_preserving_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    unique: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        unique.append(item)
    return unique


def swift_string(value: Any) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def build_binding(surface_id: str) -> dict[str, Any]:
    packet = enrich_packet_with_instrument(combined_surface_payload(surface_id))
    instrument = packet.get("signature_visual_instrument", {}) if isinstance(packet.get("signature_visual_instrument"), dict) else {}
    proof_status = proof_binding_status(str(packet.get("proof_status")))
    implementation_status = str(packet.get("implementation_status"))
    last_receipt = None
    receipt_dir = REPORT_DIR / "frontend-implementation-receipts"
    if receipt_dir.exists():
        for candidate in sorted(receipt_dir.glob(f"{surface_id}*.json")):
            last_receipt = str(candidate.relative_to(Path.cwd()))
            break
    future_visual_files = list(instrument.get("future_visual_object_source_files", []) or [])
    declared_files = list(packet.get("source_candidates", []) or [])
    visual_object_file = next((path for path in declared_files if surface_id.split("_")[0].lower() in path.lower()), None)
    return {
        "surface_id": surface_id,
        "recipe_id": packet.get("recipe_id"),
        "destination": packet.get("destination"),
        "primary_object": packet.get("primary_object"),
        "maturity_tier": packet.get("maturity_tier"),
        "source_relationship": packet.get("source_relationship"),
        "source_candidates": declared_files,
        "declared_implementation_files": declared_files,
        "generated_swift_identifier": f"AmbitionsSurfaceID.{generated_swift_case_name(surface_id)}",
        "signature_instrument_id": instrument.get("signature_instrument_id"),
        "signature_instrument_name": instrument.get("signature_instrument_name"),
        "shared_instrument_primitives": instrument.get("shared_instrument_primitives", []),
        "visual_object_source_file": visual_object_file,
        "future_visual_object_source_file": future_visual_files[0] if future_visual_files else None,
        "future_visual_object_source_files": future_visual_files,
        "instrument_implementation_status": instrument.get("instrument_implementation_status"),
        "instrument_required": instrument.get("instrument_required"),
        "preview_targets": packet.get("performance_preview_requirements", {}).get("preview_targets", []),
        "test_targets": ["AmbitionsTests", "AmbitionsUITests"],
        "implementation_status": implementation_status,
        "proof_status": proof_status,
        "last_receipt": last_receipt,
        "known_gaps": packet.get("known_gaps", []),
    }


def write_generated_swift_files(bindings: list[dict[str, Any]]) -> list[str]:
    root_cases = unique_preserving_order([row["surface_universe_id"] for row in universe_rows()])
    recipe_cases = unique_preserving_order([row["recipe_inventory_id"] if row.get("recipe_inventory_id") else row["surface_universe_id"] for row in universe_rows()])
    destination_cases = sorted({str(row.get("destination")) for row in universe_rows() if row.get("destination")})
    unique_bindings = list({str(binding["surface_id"]): binding for binding in bindings}.values())

    surface_lines = [
        "// Generated by scripts/ambitions-frontend-source-bindings.py",
        "import Foundation",
        "",
        "public enum AmbitionsSurfaceID: String, CaseIterable, Sendable {",
    ]
    surface_lines.extend(f"    case {case} = \"{case}\"" for case in root_cases)
    surface_lines.append("}")

    recipe_lines = [
        "// Generated by scripts/ambitions-frontend-source-bindings.py",
        "import Foundation",
        "",
        "public enum AmbitionsRecipeID: String, CaseIterable, Sendable {",
    ]
    recipe_lines.extend(f"    case {case} = \"{case}\"" for case in recipe_cases)
    recipe_lines.append("}")

    destination_lines = [
        "// Generated by scripts/ambitions-frontend-source-bindings.py",
        "import Foundation",
        "",
        "public enum AmbitionsDestinationID: String, CaseIterable, Sendable {",
    ]
    for destination in destination_cases:
        case_name = generated_destination_case_name(destination)
        destination_lines.append(f"    case {case_name} = \"{destination}\"")
    destination_lines.extend(
        [
            "}",
            "",
            "public struct AmbitionsFrontendAuthorityRecord: Sendable {",
            "    public let surfaceID: AmbitionsSurfaceID",
            "    public let recipeID: AmbitionsRecipeID",
            "    public let destination: AmbitionsDestinationID",
            "    public let primaryObject: String",
            "    public let maturityTier: String",
            "    public let sourceRelationship: String",
            "    public let proofStatus: String",
            "    public let signatureInstrumentID: String?",
            "    public let instrumentImplementationStatus: String",
            "}",
            "",
            "public enum AmbitionsFrontendAuthority {",
            "    public static let records: [AmbitionsSurfaceID: AmbitionsFrontendAuthorityRecord] = [",
        ]
    )
    record_lines: list[str] = []
    for binding in unique_bindings:
        destination_case = generated_destination_case_name(str(binding["destination"]))
        surface_case = str(binding["surface_id"])
        recipe_case = str(binding["recipe_id"])
        instrument_id = binding.get("signature_instrument_id")
        instrument_expr = "nil" if not instrument_id else swift_string(instrument_id)
        record_lines.append(
            f"        .{surface_case}: AmbitionsFrontendAuthorityRecord(surfaceID: .{surface_case}, recipeID: .{recipe_case}, destination: .{destination_case}, primaryObject: {swift_string(binding['primary_object'])}, maturityTier: {swift_string(binding['maturity_tier'])}, sourceRelationship: {swift_string(binding['source_relationship'])}, proofStatus: {swift_string(binding['proof_status'])}, signatureInstrumentID: {instrument_expr}, instrumentImplementationStatus: {swift_string(binding.get('instrument_implementation_status'))})"
        )
    destination_lines.extend(f"{line}{',' if index < len(record_lines) - 1 else ''}" for index, line in enumerate(record_lines))
    destination_lines.extend(["    ]", "}", ""])

    generated_paths = []
    path_map = {
        Path("Sources/Theme/AmbitionsSurfaceID.generated.swift"): "\n".join(surface_lines) + "\n",
        Path("Sources/Theme/AmbitionsRecipeID.generated.swift"): "\n".join(recipe_lines) + "\n",
        Path("Sources/Theme/AmbitionsFrontendAuthority.generated.swift"): "\n".join(destination_lines) + "\n",
    }
    for path, text in path_map.items():
        write_text(Path(path), text)
        generated_paths.append(str(path))
    return generated_paths


def render_md(report: dict[str, Any]) -> str:
    lines = [
        "# Frontend Source Bindings",
        "",
        f"Batch: `{report['batch_id']}`",
        f"Surface count: `{report['surface_count']}`",
        "",
        "## Counts",
        f"- implementation status: {report['implementation_status_counts']}",
        f"- proof status: {report['proof_status_counts']}",
        f"- destination counts: {report['destination_counts']}",
        f"- signature instruments: {report['signature_instrument_counts']}",
        "",
        "## Missing Top-Level Instruments",
    ]
    for surface_id in report["missing_top_level_instruments"] or ["None"]:
        lines.append(f"- `{surface_id}`")
    lines.extend(["", "## Missing Receipts"])
    for surface_id in report["surfaces_missing_receipts"]:
        lines.append(f"- `{surface_id}`")
    lines.extend(["", "## Top Gaps"])
    for item in report["top_gaps"]:
        lines.append(f"- `{item}`")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    bindings = [build_binding(row["surface_universe_id"]) for row in universe_rows()]
    write_json_like_yaml(
        SOURCE_BINDINGS_PATH,
        {
            "schema_version": 1,
            "generated_from_batch": BATCH_ID,
            "bindings": bindings,
        },
    )
    generated_swift_paths = write_generated_swift_files(bindings)
    report = {
        "batch_id": BATCH_ID,
        "generated_from_batch": BATCH_ID,
        "surface_count": len(bindings),
        "destination_counts": surface_counts_by("destination"),
        "implementation_status_counts": dict(sorted(Counter(binding["implementation_status"] for binding in bindings).items())),
        "proof_status_counts": dict(sorted(Counter(binding["proof_status"] for binding in bindings).items())),
        "signature_instrument_counts": instrument_counts([{"surface_id": binding["surface_id"], "signature_visual_instrument": {"signature_instrument_id": binding.get("signature_instrument_id")}} for binding in bindings]),
        "missing_top_level_instruments": missing_top_level_instruments([{"surface_id": binding["surface_id"], "signature_visual_instrument": {"signature_instrument_id": binding.get("signature_instrument_id")}} for binding in bindings]),
        "source_linked_surfaces": [binding["surface_id"] for binding in bindings if binding["source_relationship"] == "implemented_source_present"],
        "canon_only_pending_lock_surfaces": [binding["surface_id"] for binding in bindings if binding["implementation_status"] == "canon_only_pending_lock"],
        "source_approximation_surfaces": [binding["surface_id"] for binding in bindings if binding["implementation_status"] == "source_approximation_present"],
        "implemented_unproven_surfaces": [binding["surface_id"] for binding in bindings if binding["implementation_status"] == "implemented_unproven"],
        "proven_surfaces": [binding["surface_id"] for binding in bindings if binding["implementation_status"] == "proven"],
        "surfaces_with_receipts": [binding["surface_id"] for binding in bindings if binding["last_receipt"]],
        "surfaces_missing_receipts": [binding["surface_id"] for binding in bindings if not binding["last_receipt"]],
        "p0_surfaces_ready_for_implementation": [binding["surface_id"] for binding in bindings if binding["maturity_tier"] == "P0" and binding["source_relationship"] == "implemented_source_present"],
        "p0_surfaces_blocked_by_missing_source_binding": [],
        "top_gaps": dedupe([gap for binding in bindings for gap in binding.get("known_gaps", []) if gap])[:20],
        "generated_swift_paths": generated_swift_paths,
        "bindings": bindings,
    }
    write_json(REPORT_DIR / "frontend-source-bindings.json", report)
    write_text(REPORT_DIR / "frontend-source-bindings.md", render_md(report))
    print("GREEN")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
