#!/usr/bin/env python3
"""Human code-quality gate for Ambitions app source and tests.

The gate is intentionally conservative. It flags high-signal prompt/process
residue, stale user-facing Plan/Profile copy, unowned TODO-style comments,
generated-looking comments, direct SwiftData leakage outside persistence
boundaries, and forbidden backend/provider terms in app runtime code.

The gate also distinguishes preview-only source, compatibility seams, guardrail
constants, and owned large-file seams so those categories can be documented
precisely without producing noisy warnings.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROOTS = [
    ROOT / "Native/Ambitions",
    ROOT / "Native/AmbitionsTests",
    ROOT / "Native/AmbitionsWidgetExtension",
    ROOT / "Native/AmbitionsShareExtension",
    ROOT / "Sources",
    ROOT / "AppUI/Sources",
]
ALLOWED_SWIFTDATA_ROOTS = [
    ROOT / "Native/Ambitions/Persistence",
    ROOT / "Native/AmbitionsTests/Persistence",
]
PREVIEW_ONLY_ROOTS = [
    ROOT / "Native/Ambitions/PreviewSupport",
    ROOT / "Sources/Previews",
]
TEST_ROOTS = [
    ROOT / "Native/AmbitionsTests",
]
COMPATIBILITY_ROOTS = [
    ROOT / "Native/Ambitions/Features/Plan",
]
GUARDRAIL_CONSTANT_FILES = {
    "Native/Ambitions/Domain/DomainPackageBoundaryModels.swift",
    "Native/Ambitions/Domain/ScreenContractModels.swift",
    "Native/Ambitions/Features/FeatureEnginePackageBoundaryModels.swift",
    "Native/Ambitions/Persistence/StoragePackageBoundaryModels.swift",
    "Native/Ambitions/Runtime/RuntimePackageBoundaryModels.swift",
}
OWNED_LARGE_FILE_EXCEPTIONS = {
    "Native/Ambitions/Features/Goals/GoalsFeatureModels.swift",
    "Native/Ambitions/Features/Goals/GoalsFeatureService.swift",
    "Native/Ambitions/Features/Time/TimeFeatureService.swift",
    "Native/Ambitions/Features/You/YouFeatureService.swift",
    "Native/Ambitions/Features/You/YouScreen.swift",
    "Native/Ambitions/Features/Today/TodayFeatureService.swift",
}
TEXT_EXTENSIONS = {".swift", ".txt", ".json", ".yml", ".yaml", ".plist", ".strings", ".entitlements"}
FILE_NAME_HINTS = {"manager", "helper", "utils", "data", "viewmodel", "service"}

FORBIDDEN_BACKEND_PATTERNS = [
    re.compile(r"\bSupabase\b", re.I),
    re.compile(r"\bFirebase\b", re.I),
    re.compile(r"\bPostgres\b", re.I),
    re.compile(r"\bOpenAI\b", re.I),
    re.compile(r"\bChatGPT\b", re.I),
    re.compile(r"\bLLM\b", re.I),
    re.compile(r"\banalytics\b", re.I),
    re.compile(r"\btelemetry\b", re.I),
    re.compile(r"\bCloudKit\b", re.I),
    re.compile(r"\bCKContainer\b", re.I),
    re.compile(r"\bNSUbiquitous\b", re.I),
]

TODO_PATTERN = re.compile(r"\b(TODO|FIXME|HACK)\b", re.I)
OWNED_TODO_HINT = re.compile(r"\b(owner|follow[- ]?up|tracked|ticket|issue|batch)\b", re.I)
GENERATED_COMMENT_HINTS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "this file was generated",
)
STRING_UI_HINTS = ("Text(", "Label(", "title", "subtitle", "eyebrow", "placeholder", "description", "message", "copy", "hint")
GENERIC_TYPE_PATTERN = re.compile(r"\b(class|struct|enum|actor)\s+(Manager|Helper|Utils|Data|ViewModel|Service)\b")
SWIFTDATA_PATTERN = re.compile(r"\bimport\s+SwiftData\b|\bModelContext\b|\bModelContainer\b|\bFetchDescriptor\b|@Model\b")

SIZE_FAIL = 2000
STRUCTURED_PROMPT_PATTERN = re.compile(
    r"\bprompt\s*:"
    r"|\b(let|var)\s+prompt\b"
    r"|\bprompt\s*,"
    r"|\bprompt\s+in\b"
    r"|\bprompt\.(title|detail|actionLabel|isEmpty)\b"
    r"|\.prompt\b"
    r"|\bcorrectionPrompts\b",
    re.I,
)
PRODUCT_PROMPT_PHRASES = (
    "milestone prompt",
    "recovery prompt",
    "review prompt",
    "prompt rating",
    "external prompt",
    "authorization prompt",
    "show a prompt",
    "history to show a prompt",
)
PROCESS_LITERAL_PATTERNS = [
    ("codex", re.compile(r"\bCodex\b", re.I)),
    ("batch", re.compile(r"\bbatch\b", re.I)),
    ("prompt", re.compile(r"\bprompt\b", re.I)),
    ("runner", re.compile(r"\brunner\b", re.I)),
    ("closeout", re.compile(r"\bcloseout\b", re.I)),
    ("accepted-yellow", re.compile(r"\bAccepted Yellow\b", re.I)),
    ("green-closeout", re.compile(r"\bGreen closeout\b", re.I)),
    ("phase", re.compile(r"\bPhase 0[1-4]\b", re.I)),
]


@dataclass
class Finding:
    severity: str
    path: Path
    line: int | None
    category: str
    message: str


def iter_files(roots: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        if root.is_file():
            if root.suffix in TEXT_EXTENSIONS:
                files.append(root)
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix in TEXT_EXTENSIONS:
                files.append(path)
    return sorted(set(files))


def path_is_within(path: Path, roots: list[Path]) -> bool:
    for root in roots:
        try:
            path.relative_to(root)
            return True
        except ValueError:
            continue
    return False


def is_text_file(path: Path) -> bool:
    return path.suffix in TEXT_EXTENSIONS


def allowed_swiftdata(path: Path) -> bool:
    return path_is_within(path, ALLOWED_SWIFTDATA_ROOTS)


def is_preview_only(path: Path) -> bool:
    return path_is_within(path, PREVIEW_ONLY_ROOTS)


def is_test_source(path: Path) -> bool:
    return path_is_within(path, TEST_ROOTS)


def is_compatibility_seam(path: Path) -> bool:
    return path_is_within(path, COMPATIBILITY_ROOTS)


def is_guardrail_constant(path: Path, line: str) -> bool:
    relative_path = path.relative_to(ROOT).as_posix()
    if relative_path not in GUARDRAIL_CONSTANT_FILES:
        return False
    guardrail_tokens = (
        "forbiddenImports",
        "forbiddenFirstScreenContent",
        "forbiddenNoCopy",
        "guardrail",
        "boundary",
    )
    return any(token in line for token in guardrail_tokens)


def is_generated_source(path: Path) -> bool:
    relative_path = path.relative_to(ROOT).as_posix()
    return relative_path.endswith(".generated.swift") or relative_path == "Native/Ambitions/Persistence/LegacyImportService.swift"


def is_owned_large_file(path: Path) -> bool:
    return path.relative_to(ROOT).as_posix() in OWNED_LARGE_FILE_EXCEPTIONS


def is_legitimate_prompt_reference(line: str) -> bool:
    lowered = line.lower()
    return bool(STRUCTURED_PROMPT_PATTERN.search(line)) or any(phrase in lowered for phrase in PRODUCT_PROMPT_PHRASES)


def is_process_trace_line(path: Path, line: str) -> bool:
    if is_preview_only(path) or is_test_source(path) or is_compatibility_seam(path):
        return False
    if is_guardrail_constant(path, line):
        return False
    relative_path = path.relative_to(ROOT).as_posix()
    if "AmbitionsOSCloseoutTailGate" in relative_path:
        return False
    return True


def app_runtime_source(path: Path) -> bool:
    runtime_roots = [
        ROOT / "Native/Ambitions",
        ROOT / "Native/AmbitionsWidgetExtension",
        ROOT / "Native/AmbitionsShareExtension",
        ROOT / "Sources",
        ROOT / "AppUI/Sources",
    ]
    non_runtime_roots = PREVIEW_ONLY_ROOTS
    return path_is_within(path, runtime_roots) and not path_is_within(path, non_runtime_roots)


def scan_file(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    relative_path = path.relative_to(ROOT).as_posix()
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    if len(lines) > SIZE_FAIL and not is_preview_only(path) and not is_test_source(path) and not is_compatibility_seam(path) and not is_owned_large_file(path):
        severity = "fail"
        findings.append(
            Finding(
                severity=severity,
                path=path,
                line=None,
                category="file-size",
                message=f"{len(lines)} lines (fail>{SIZE_FAIL})",
            )
        )

    if path.stem.lower() in FILE_NAME_HINTS:
        findings.append(
            Finding(
                severity="warning",
                path=path,
                line=None,
                category="generic-name",
                message=f"generic filename stem {path.stem!r}",
            )
        )

    for idx, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped:
            continue

        if TODO_PATTERN.search(line) and not OWNED_TODO_HINT.search(line):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="todo-without-owner",
                    message=line.strip(),
                )
            )

        if any(hint in line.lower() for hint in GENERATED_COMMENT_HINTS) and not is_preview_only(path) and not is_test_source(path) and not is_generated_source(path):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="generated-comment",
                    message=line.strip(),
                )
            )

        if is_process_trace_line(path, line):
            for name, pattern in PROCESS_LITERAL_PATTERNS:
                if pattern.search(line):
                    if name == "prompt" and is_legitimate_prompt_reference(line):
                        break
                    if name == "codex" and "docs/codex/" in line:
                        break
                    severity = "fail" if app_runtime_source(path) else "warning"
                    findings.append(
                        Finding(
                            severity=severity,
                            path=path,
                            line=idx,
                            category=f"process-residue:{name}",
                            message=line.strip(),
                        )
                    )
                    break

        if '"' in line and any(hint in line for hint in STRING_UI_HINTS):
            if re.search(r"\bPlan\b", line) and not relative_path.startswith("Native/Ambitions/Features/Plan/") and not relative_path.startswith("Native/AmbitionsTests/") and not is_preview_only(path):
                findings.append(
                    Finding(
                        severity="warning",
                        path=path,
                        line=idx,
                        category="stale-plan-copy",
                        message=line.strip(),
                    )
                )
            if re.search(r"\bProfile\b", line) and not relative_path.startswith("Native/Ambitions/Features/Profile/") and not relative_path.startswith("Native/AmbitionsTests/") and not is_preview_only(path):
                findings.append(
                    Finding(
                        severity="warning",
                        path=path,
                        line=idx,
                        category="stale-profile-copy",
                        message=line.strip(),
                    )
                )

        if SWIFTDATA_PATTERN.search(line) and not allowed_swiftdata(path):
            severity = "fail" if not path_is_within(path, [ROOT / "Native/AmbitionsTests"]) else "warning"
            findings.append(
                Finding(
                    severity=severity,
                    path=path,
                    line=idx,
                    category="swiftdata-leak",
                    message=line.strip(),
                )
            )

        for pattern in FORBIDDEN_BACKEND_PATTERNS:
            if pattern.search(line):
                if is_guardrail_constant(path, line) or is_preview_only(path) or is_test_source(path) or is_generated_source(path):
                    break
                severity = "warning"
                findings.append(
                    Finding(
                        severity=severity,
                        path=path,
                        line=idx,
                        category="forbidden-backend",
                        message=line.strip(),
                    )
                )
                break

        if GENERIC_TYPE_PATTERN.search(line):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="generic-name",
                    message=line.strip(),
                )
            )

    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Optional paths to scan instead of the default app/test roots.")
    args = parser.parse_args()

    roots = [ROOT / path for path in args.paths] if args.paths else DEFAULT_ROOTS
    files = iter_files(roots)

    findings: list[Finding] = []
    for path in files:
        try:
            findings.extend(scan_file(path))
        except UnicodeDecodeError:
            continue

    blocking = [finding for finding in findings if finding.severity == "fail"]
    warnings = [finding for finding in findings if finding.severity != "fail"]

    print("# Ambitions Human Code Quality Gate")
    print(f"scanned_files: {len(files)}")
    print(f"blocking_findings: {len(blocking)}")
    print(f"warnings: {len(warnings)}")

    for finding in sorted(warnings, key=lambda item: (str(item.path), item.line or 0, item.category)):
        location = f"{finding.path.relative_to(ROOT)}"
        if finding.line is not None:
            location = f"{location}:{finding.line}"
        print(f"YELLOW: {finding.category}: {location}: {finding.message}")

    if blocking:
        for finding in sorted(blocking, key=lambda item: (str(item.path), item.line or 0, item.category)):
            location = f"{finding.path.relative_to(ROOT)}"
            if finding.line is not None:
                location = f"{location}:{finding.line}"
            print(f"RED: {finding.category}: {location}: {finding.message}", file=sys.stderr)
        return 1

    if warnings:
        return 1

    print("GREEN: no human-code-quality findings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
