#!/usr/bin/env python3
"""Collect conservative source-disposition facts without modifying source files."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath


CANONICAL_RETAINED = "canonical_retained"
CANONICAL_CONSOLIDATE = "canonical_requires_consolidation"
MISOWNED_REQUIRED = "misowned_required"
DUPLICATE_AUTHORITY = "duplicate_authority"
OBSOLETE_SHIM = "obsolete_compatibility_shim"
HISTORICAL_RESIDUE = "historical_residue"
GENERATED = "generated_source"
TEST_PREVIEW_ONLY = "test_preview_only"
UNKNOWN = "unknown_pending_stronger_evidence"

PRODUCTION_ROOTS = (
    "Native/Ambitions",
    "Native/AmbitionsWidgetExtension",
    "Native/AmbitionsShareExtension",
    "Packages/AmbitionsDesignSystem/Sources",
    "Packages/AmbitionsDesignSystem/AppUI/Sources",
)
EXCLUDED_ROOTS = ("Native/AmbitionsTests", "Native/AmbitionsUITests")
NOMINAL_DECLARATION_RE = re.compile(
    r"\b(class|struct|enum|protocol|actor|typealias)\s+([A-Za-z_]\w*)"
)
EXTENSION_RE = re.compile(r"\bextension\s+([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)")
FUNCTION_RE = re.compile(r"\bfunc\s+([A-Za-z_]\w*|[!%&*+\-./<=>?@^|~]+)")
PROPERTY_RE = re.compile(
    r"(?m)^\s*(?:(?:public|internal|private|fileprivate|open|static|class|lazy|weak|unowned|nonisolated)\s+)*"
    r"(var|let)\s+([A-Za-z_]\w*)"
)
OPERATOR_DECLARATION_RE = re.compile(r"\b(?:prefix|postfix|infix)\s+operator\s+([!%&*+\-./<=>?@^|~]+)")
PRECEDENCEGROUP_RE = re.compile(r"\bprecedencegroup\s+([A-Za-z_]\w*)")
INIT_DEINIT_RE = re.compile(r"\b(init|deinit)\s*(?:[?!])?\s*(?=\(|\{)")
SUBSCRIPT_RE = re.compile(r"\b(subscript)\s*\(")
IMPORT_RE = re.compile(r"(?m)^\s*(?:@testable\s+)?import\s+([A-Za-z_]\w*)")
IDENTIFIER_RE = re.compile(r"\b[A-Za-z_]\w*\b")

DISCOVERY_PATTERNS = {
    "app_intents": re.compile(r"\b(?:AppIntent|AppEntity|AppShortcutsProvider|EntityQuery)\b|\bimport\s+AppIntents\b"),
    "swiftdata": re.compile(r"@Model\b|\b(?:ModelContainer|ModelContext|PersistentModel|SwiftData)\b"),
    "reflection": re.compile(r"\b(?:Mirror|reflecting|NSClassFromString|StringFromClass)\b"),
    "extension": re.compile(r"(?m)^\s*extension\s+"),
    "preview": re.compile(r"#Preview\b|\bPreviewProvider\b"),
    "registry": re.compile(r"\b(?:Registry|register|registration|resolver|container)\b", re.IGNORECASE),
    "persistence": re.compile(r"\b(?:ModelContainer|ModelContext|SwiftData|UserDefaults|FileManager|Codable)\b"),
}
MIGRATION_REPLAY_PATTERNS = {
    "migration": re.compile(r"\b(?:Migration|SchemaMigrationPlan|VersionedSchema|migrate)\w*\b", re.IGNORECASE),
    "replay": re.compile(r"\b(?:Replay|replay|rehydrat|event log)\w*\b", re.IGNORECASE),
}
GENERATED_RE = re.compile(r"generated by|do not edit|@generated", re.IGNORECASE)
REGISTRY_REFERENCE_RE = re.compile(r"\b(?:register|resolve|Registry)\b", re.IGNORECASE)


def _is_under(path: str, root: str) -> bool:
    return path == root or path.startswith(root + "/")


def production_swift_files(root: Path) -> list[Path]:
    files: dict[str, Path] = {}
    for relative_root in PRODUCTION_ROOTS:
        source_root = root / relative_root
        if not source_root.exists():
            continue
        for path in source_root.rglob("*.swift"):
            relative = path.relative_to(root).as_posix()
            if any(_is_under(relative, excluded) for excluded in EXCLUDED_ROOTS):
                continue
            files[relative] = path
    return [files[key] for key in sorted(files)]


def _declarations(text: str) -> list[dict[str, str]]:
    declarations: set[tuple[str, str]] = set(NOMINAL_DECLARATION_RE.findall(text))
    declarations.update(("extension", name) for name in EXTENSION_RE.findall(text))
    declarations.update(("func", name) for name in FUNCTION_RE.findall(text))
    declarations.update(PROPERTY_RE.findall(text))
    declarations.update(("operator", name) for name in OPERATOR_DECLARATION_RE.findall(text))
    declarations.update(("precedencegroup", name) for name in PRECEDENCEGROUP_RE.findall(text))
    declarations.update((name, name) for name in INIT_DEINIT_RE.findall(text))
    declarations.update(("subscript", name) for name in SUBSCRIPT_RE.findall(text))
    return [{"kind": kind, "name": name} for kind, name in sorted(declarations)]


def _markers(text: str, patterns: dict[str, re.Pattern[str]]) -> list[str]:
    return sorted(name for name, pattern in patterns.items() if pattern.search(text))


def _suffix_signals(path: str) -> list[str]:
    name = PurePosixPath(path).name
    signals = []
    if re.search(r"\+(?:0[2-9]|[1-9]\d*)\.swift$", name):
        signals.append("numbered_suffix_split")
    if name == "Models.swift":
        signals.append("broad_models_filename")
    if re.search(r"(?:Shim|Compatibility|Legacy)\.swift$", name, re.IGNORECASE):
        signals.append("compatibility_filename")
    return signals


def _disposition(path: str, text: str, discovery: list[str], migration: list[str]) -> tuple[str, list[str]]:
    runtime_uncertainty = [marker for marker in discovery if marker != "preview"]
    if runtime_uncertainty or migration:
        evidence = ["dynamic discovery, persistence, migration, or replay uncertainty outranks generated/preview classification"]
        if discovery:
            evidence.append("dynamic discovery markers: " + ", ".join(discovery))
        if migration:
            evidence.append("migration/replay markers: " + ", ".join(migration))
        return UNKNOWN, evidence
    if GENERATED_RE.search(text):
        return GENERATED, ["explicit generated-source marker"]
    if "/PreviewSupport/" in f"/{path}":
        return TEST_PREVIEW_ONLY, ["file is owned by the explicit PreviewSupport root"]
    evidence = ["conservative default: static evidence is insufficient for destructive classification"]
    if discovery:
        evidence.append("dynamic discovery markers: " + ", ".join(discovery))
    if migration:
        evidence.append("migration/replay markers: " + ", ".join(migration))
    return UNKNOWN, evidence


def collect_inventory(
    root: Path,
    xcode_target_membership: dict[str, list[str]],
    swiftpm_target_membership: dict[str, list[str]] | None = None,
) -> dict:
    root = root.resolve()
    swiftpm_target_membership = swiftpm_target_membership or {}
    paths = production_swift_files(root)
    records = []
    global_tokens: Counter[str] = Counter()
    registry_tokens: Counter[str] = Counter()

    for file_path in paths:
        relative = file_path.relative_to(root).as_posix()
        text = file_path.read_text(encoding="utf-8", errors="replace")
        declarations = _declarations(text)
        tokens = Counter(IDENTIFIER_RE.findall(text))
        global_tokens.update(tokens)
        for line in text.splitlines():
            if REGISTRY_REFERENCE_RE.search(line):
                registry_tokens.update(IDENTIFIER_RE.findall(line))
        records.append((relative, text, declarations, tokens))

    rows = []
    for relative, text, declarations, own_tokens in records:
        discovery = _markers(text, DISCOVERY_PATTERNS)
        migration = _markers(text, MIGRATION_REPLAY_PATTERNS)
        disposition, evidence = _disposition(relative, text, discovery, migration)
        reference_count = 0
        registry_count = 0
        for declaration in declarations:
            name = declaration["name"]
            if IDENTIFIER_RE.fullmatch(name):
                reference_count += max(0, global_tokens[name] - own_tokens[name])
                registry_count += registry_tokens[name]
            else:
                external_text = "\n".join(record[1] for record in records if record[0] != relative)
                reference_count += external_text.count(name)
        xcode_memberships = sorted(set(xcode_target_membership.get(relative, [])))
        swiftpm_memberships = sorted(set(swiftpm_target_membership.get(relative, [])))
        memberships = sorted(set(xcode_memberships + swiftpm_memberships))
        if xcode_memberships:
            evidence.append("generated Xcode target membership: " + ", ".join(xcode_memberships))
        if swiftpm_memberships:
            evidence.append("SwiftPM target membership: " + ", ".join(swiftpm_memberships))
        if declarations:
            evidence.append(f"declared symbols: {len(declarations)}; external lexical references: {reference_count}")
        else:
            evidence.append("no nominal type declarations detected")
        rows.append(
            {
                "path": relative,
                "target_membership": memberships,
                "xcode_target_membership": xcode_memberships,
                "swiftpm_target_membership": swiftpm_memberships,
                "declarations": declarations,
                "reference_count": reference_count,
                "imports": sorted(set(IMPORT_RE.findall(text))),
                "suffix_signals": _suffix_signals(relative),
                "loc": len(text.splitlines()),
                "discovery_markers": discovery,
                "migration_replay_markers": migration,
                "preview_marker": bool(DISCOVERY_PATTERNS["preview"].search(text) or "/PreviewSupport/" in f"/{relative}"),
                "generated_marker": bool(GENERATED_RE.search(text)),
                "registry_reference_count": registry_count,
                "disposition": disposition,
                "evidence": evidence,
            }
        )
    return {"schema_version": 1, "files": rows}


def target_membership_from_pbx_json(data: dict) -> dict[str, list[str]]:
    objects = data.get("objects", {})
    parent: dict[str, str] = {}
    for object_id, obj in objects.items():
        if obj.get("isa") in {"PBXGroup", "PBXVariantGroup"}:
            for child in obj.get("children", []):
                parent[child] = object_id

    path_cache: dict[str, str] = {}

    def object_path(object_id: str) -> str:
        if object_id in path_cache:
            return path_cache[object_id]
        obj = objects.get(object_id, {})
        part = obj.get("path") or obj.get("name") or ""
        if obj.get("sourceTree") == "SOURCE_ROOT" or object_id not in parent:
            result = part
        else:
            prefix = object_path(parent[object_id])
            result = f"{prefix}/{part}" if prefix and part else prefix or part
        result = str(PurePosixPath(result)) if result else ""
        path_cache[object_id] = result
        return result

    build_file_to_path = {}
    for object_id, obj in objects.items():
        if obj.get("isa") == "PBXBuildFile" and obj.get("fileRef"):
            build_file_to_path[object_id] = object_path(obj["fileRef"])

    membership: defaultdict[str, set[str]] = defaultdict(set)
    for target in objects.values():
        if target.get("isa") != "PBXNativeTarget":
            continue
        target_name = target.get("name", "<unnamed>")
        for phase_id in target.get("buildPhases", []):
            phase = objects.get(phase_id, {})
            if phase.get("isa") != "PBXSourcesBuildPhase":
                continue
            for build_file_id in phase.get("files", []):
                path = build_file_to_path.get(build_file_id)
                if path:
                    membership[path].add(target_name)
    return {path: sorted(names) for path, names in sorted(membership.items())}


def swiftpm_membership_from_description(data: dict, package_path: Path) -> dict[str, list[str]]:
    membership: defaultdict[str, set[str]] = defaultdict(set)
    package_prefix = package_path.as_posix().rstrip("/")
    described_package = Path(data.get("path", "."))
    for target in data.get("targets", []):
        target_name = target.get("name")
        target_path = Path(target.get("path", "."))
        if target_path.is_absolute():
            try:
                target_path = target_path.relative_to(described_package)
            except ValueError as error:
                raise ValueError(f"SwiftPM target path is outside described package: {target_path}") from error
        if not target_name:
            raise ValueError("SwiftPM target is missing a name")
        for source in target.get("sources", []):
            source_path = Path(source)
            if source_path.is_absolute():
                try:
                    source_path = source_path.relative_to(described_package)
                except ValueError as error:
                    raise ValueError(f"SwiftPM source is outside described package: {source_path}") from error
                relative = source_path
            elif source_path.parts[: len(target_path.parts)] == target_path.parts:
                relative = source_path
            else:
                relative = target_path / source_path
            canonical = (PurePosixPath(package_prefix) / PurePosixPath(relative.as_posix())).as_posix()
            membership[canonical].add(target_name)
    return {path: sorted(names) for path, names in sorted(membership.items())}


def load_pbx_json(project: Path) -> dict:
    pbxproj = project / "project.pbxproj" if project.is_dir() else project
    result = subprocess.run(
        ["plutil", "-convert", "json", "-o", "-", str(pbxproj)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def load_swiftpm_membership(package_path: Path) -> dict[str, list[str]]:
    result = subprocess.run(
        ["swift", "package", "--package-path", str(package_path), "describe", "--type", "json"],
        check=True,
        capture_output=True,
        text=True,
    )
    try:
        description = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError(f"SwiftPM describe returned invalid JSON for {package_path}") from error
    membership = swiftpm_membership_from_description(description, package_path)
    if not membership:
        raise RuntimeError(f"SwiftPM describe returned no source membership for {package_path}")
    return membership


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = Path.cwd()
    xcode_membership = target_membership_from_pbx_json(load_pbx_json(args.project))
    package_path = Path("Packages/AmbitionsDesignSystem")
    swiftpm_membership = load_swiftpm_membership(package_path)
    inventory = collect_inventory(root, xcode_membership, swiftpm_membership)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    counts = Counter(row["disposition"] for row in inventory["files"])
    print(f"inventory-files={len(inventory['files'])}")
    print("dispositions=" + json.dumps(dict(sorted(counts.items())), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
