#!/usr/bin/env python3
"""Human code-quality gate for Ambitions app source and tests.

The gate is intentionally conservative. It flags high-signal prompt/process
residue, stale user-facing Plan/Profile copy, unowned TODO-style comments,
generated-looking comments, direct SwiftData leakage outside persistence
boundaries, and forbidden backend/provider terms in app runtime code.

Size findings are reported as warnings only so the gate can stay focused on
actionable code-quality regressions rather than routine extraction backlogs.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROOTS = [
    ROOT / "Native/Ambitions",
    ROOT / "Native/AmbitionsTests",
    ROOT / "Native/AmbitionsWidgetExtension",
    ROOT / "Native/AmbitionsShareExtension",
    ROOT / "Sources",
    ROOT / "AppUI/Sources",
]
ALLOWED_SWIFTDATA_ROOTS = [
    ROOT / "Native/Ambitions/Persistence",
    ROOT / "Native/AmbitionsTests/Persistence",
]
TEXT_EXTENSIONS = {".swift", ".txt", ".json", ".yml", ".yaml", ".plist", ".strings", ".entitlements"}
FILE_NAME_HINTS = {"manager", "helper", "utils", "data", "viewmodel", "service"}

PROCESS_PATTERNS = [
    ("codex", re.compile(r"\bCodex\b", re.I), True),
    ("batch", re.compile(r"\bbatch\b", re.I), True),
    ("prompt", re.compile(r"\bprompt\b", re.I), False),
    ("runner", re.compile(r"\brunner\b", re.I), True),
    ("closeout", re.compile(r"\bcloseout\b", re.I), True),
    ("accepted-yellow", re.compile(r"\bAccepted Yellow\b", re.I), True),
    ("green-closeout", re.compile(r"\bGreen closeout\b", re.I), True),
    ("phase", re.compile(r"\bPhase 0[1-4]\b", re.I), True),
]

FORBIDDEN_BACKEND_PATTERNS = [
    re.compile(r"\bSupabase\b", re.I),
    re.compile(r"\bFirebase\b", re.I),
    re.compile(r"\bPostgres\b", re.I),
    re.compile(r"\bOpenAI\b", re.I),
    re.compile(r"\bChatGPT\b", re.I),
    re.compile(r"\bLLM\b", re.I),
    re.compile(r"\banalytics\b", re.I),
    re.compile(r"\btelemetry\b", re.I),
    re.compile(r"\bCloudKit\b", re.I),
    re.compile(r"\bCKContainer\b", re.I),
    re.compile(r"\bNSUbiquitous\b", re.I),
]

TODO_PATTERN = re.compile(r"\b(TODO|FIXME|HACK)\b", re.I)
OWNED_TODO_HINT = re.compile(r"\b(owner|follow[- ]?up|tracked|ticket|issue|batch)\b", re.I)
GENERATED_COMMENT_HINTS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "this file was generated",
)
STRING_UI_HINTS = ("Text(", "Label(", "title", "subtitle", "eyebrow", "placeholder", "description", "message", "copy", "hint")
GENERIC_TYPE_PATTERN = re.compile(r"\b(class|struct|enum|actor)\s+(Manager|Helper|Utils|Data|ViewModel|Service)\b")
SWIFTDATA_PATTERN = re.compile(r"\bimport\s+SwiftData\b|\bModelContext\b|\bModelContainer\b|\bFetchDescriptor\b|@Model\b")

SIZE_WARN = 500
SIZE_STRONG = 800
SIZE_FAIL = 1200


@dataclass
class Finding:
    severity: str
    path: Path
    line: int | None
    category: str
    message: str


def iter_files(roots: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        if root.is_file():
            if root.suffix in TEXT_EXTENSIONS:
                files.append(root)
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix in TEXT_EXTENSIONS:
                files.append(path)
    return sorted(set(files))


def path_is_within(path: Path, roots: list[Path]) -> bool:
    for root in roots:
        try:
            path.relative_to(root)
            return True
        except ValueError:
            continue
    return False


def is_text_file(path: Path) -> bool:
    return path.suffix in TEXT_EXTENSIONS


def allowed_swiftdata(path: Path) -> bool:
    return path_is_within(path, ALLOWED_SWIFTDATA_ROOTS)


def app_runtime_source(path: Path) -> bool:
    runtime_roots = [
        ROOT / "Native/Ambitions",
        ROOT / "Native/AmbitionsWidgetExtension",
        ROOT / "Native/AmbitionsShareExtension",
        ROOT / "Sources",
        ROOT / "AppUI/Sources",
    ]
    non_runtime_roots = [
        ROOT / "Native/Ambitions/PreviewSupport",
        ROOT / "Sources/Previews",
    ]
    return path_is_within(path, runtime_roots) and not path_is_within(path, non_runtime_roots)


def scan_file(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    relative_path = path.relative_to(ROOT).as_posix()
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    if len(lines) > SIZE_WARN:
        severity = "warning"
        if len(lines) > SIZE_STRONG:
            severity = "strong-warning"
        if len(lines) > SIZE_FAIL:
            severity = "strong-warning"
        findings.append(
            Finding(
                severity=severity,
                path=path,
                line=None,
                category="file-size",
                message=f"{len(lines)} lines (warn>{SIZE_WARN}, strong>{SIZE_STRONG}, fail>{SIZE_FAIL})",
            )
        )

    if path.stem.lower() in FILE_NAME_HINTS:
        findings.append(
            Finding(
                severity="warning",
                path=path,
                line=None,
                category="generic-name",
                message=f"generic filename stem {path.stem!r}",
            )
        )

    for idx, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped:
            continue

        if TODO_PATTERN.search(line) and not OWNED_TODO_HINT.search(line):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="todo-without-owner",
                    message=line.strip(),
                )
            )

        if any(hint in line.lower() for hint in GENERATED_COMMENT_HINTS):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="generated-comment",
                    message=line.strip(),
                )
            )

        for name, pattern, blocks_runtime in PROCESS_PATTERNS:
            if pattern.search(line):
                trace_reference = "docs/codex/" in line
                severity = "fail" if blocks_runtime and app_runtime_source(path) and not trace_reference else "warning"
                findings.append(
                    Finding(
                        severity=severity,
                        path=path,
                        line=idx,
                        category=f"process-residue:{name}",
                        message=line.strip(),
                    )
                )
                break

        if '"' in line and any(hint in line for hint in STRING_UI_HINTS):
            if re.search(r"\bPlan\b", line) and not relative_path.startswith("Native/Ambitions/Features/Plan/") and not relative_path.startswith("Native/AmbitionsTests/Plan/"):
                findings.append(
                    Finding(
                        severity="warning",
                        path=path,
                        line=idx,
                        category="stale-plan-copy",
                        message=line.strip(),
                    )
                )
            if re.search(r"\bProfile\b", line) and not relative_path.startswith("Native/Ambitions/Features/Profile/") and not relative_path.startswith("Native/AmbitionsTests/Profile/"):
                findings.append(
                    Finding(
                        severity="warning",
                        path=path,
                        line=idx,
                        category="stale-profile-copy",
                        message=line.strip(),
                    )
                )

        if SWIFTDATA_PATTERN.search(line) and not allowed_swiftdata(path):
            severity = "fail" if not path_is_within(path, [ROOT / "Native/AmbitionsTests"]) else "warning"
            findings.append(
                Finding(
                    severity=severity,
                    path=path,
                    line=idx,
                    category="swiftdata-leak",
                    message=line.strip(),
                )
            )

        for pattern in FORBIDDEN_BACKEND_PATTERNS:
            if pattern.search(line):
                severity = "warning"
                if path_is_within(path, [ROOT / "Native/Ambitions", ROOT / "Native/AmbitionsWidgetExtension", ROOT / "Native/AmbitionsShareExtension", ROOT / "Sources", ROOT / "AppUI/Sources"]):
                    if "boundary" not in relative_path.lower() and "preview" not in relative_path.lower() and "test" not in relative_path.lower() and "forbidden" not in line.lower():
                        severity = "warning"
                findings.append(
                    Finding(
                        severity=severity,
                        path=path,
                        line=idx,
                        category="forbidden-backend",
                        message=line.strip(),
                    )
                )
                break

        if GENERIC_TYPE_PATTERN.search(line):
            findings.append(
                Finding(
                    severity="warning",
                    path=path,
                    line=idx,
                    category="generic-name",
                    message=line.strip(),
                )
            )

    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Optional paths to scan instead of the default app/test roots.")
    args = parser.parse_args()

    roots = [ROOT / path for path in args.paths] if args.paths else DEFAULT_ROOTS
    files = iter_files(roots)

    findings: list[Finding] = []
    for path in files:
        try:
            findings.extend(scan_file(path))
        except UnicodeDecodeError:
            continue

    blocking = [finding for finding in findings if finding.severity == "fail"]
    warnings = [finding for finding in findings if finding.severity != "fail"]

    print("# Ambitions Human Code Quality Gate")
    print(f"scanned_files: {len(files)}")
    print(f"blocking_findings: {len(blocking)}")
    print(f"warnings: {len(warnings)}")

    for finding in sorted(warnings, key=lambda item: (str(item.path), item.line or 0, item.category)):
        location = f"{finding.path.relative_to(ROOT)}"
        if finding.line is not None:
            location = f"{location}:{finding.line}"
        print(f"YELLOW: {finding.category}: {location}: {finding.message}")

    if blocking:
        for finding in sorted(blocking, key=lambda item: (str(item.path), item.line or 0, item.category)):
            location = f"{finding.path.relative_to(ROOT)}"
            if finding.line is not None:
                location = f"{location}:{finding.line}"
            print(f"RED: {finding.category}: {location}: {finding.message}", file=sys.stderr)
        return 1

    print("GREEN: no blocking human code-quality findings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
