#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

STAMP="$(date +%Y%m%d-%H%M%S)"
LOG_DIR=".codex/logs/dirty-worktree"
PATCH_DIR=".codex/patches"
REPORT="docs/audits/post-pk03-dirty-worktree-reconciliation-$STAMP.md"
LATEST_REPORT="docs/audits/post-pk03-dirty-worktree-reconciliation-latest.md"

mkdir -p "$LOG_DIR" "$PATCH_DIR" "docs/audits"

ACTIVE_BATCH="unknown"
NEXT_BATCH="unknown"
if [[ -f ".codex/state/active-batch.yml" ]]; then
  ACTIVE_BATCH="$(awk '/^[[:space:]]+batch:/ {gsub(/\"/, "", $2); print $2; exit}' .codex/state/active-batch.yml || true)"
  NEXT_BATCH="$(awk '/^[[:space:]]+next_eligible_batch:/ {sub(/^[[:space:]]+next_eligible_batch:[[:space:]]+/, ""); gsub(/\"/, ""); print; exit}' .codex/state/active-batch.yml || true)"
fi

STATUS_FILE="$LOG_DIR/status-$STAMP.txt"
UNTRACKED_FILE="$LOG_DIR/untracked-$STAMP.txt"
DIFF_FILE="$PATCH_DIR/dirty-worktree-$STAMP.patch"
STAGED_DIFF_FILE="$PATCH_DIR/dirty-worktree-staged-$STAMP.patch"
NAME_STATUS_FILE="$LOG_DIR/name-status-$STAMP.txt"

# Preserve evidence before making any decision.
git status --short > "$STATUS_FILE"
git diff > "$DIFF_FILE"
git diff --staged > "$STAGED_DIFF_FILE"
git diff --name-status > "$NAME_STATUS_FILE"
git ls-files --others --exclude-standard > "$UNTRACKED_FILE"

DIRTY_COUNT="$(wc -l < "$STATUS_FILE" | tr -d ' ')"

cat > "$REPORT" <<EOF
# Post-PK03 Dirty Worktree Reconciliation Report

<!-- markdownlint-disable MD013 -->

Date: $STAMP  
Gate: Post-PK03 Dirty Worktree Reconciliation  
Result: $([[ "$DIRTY_COUNT" == "0" ]] && echo "Green / clean" || echo "Blocked / dirty worktree requires classification")  
Active batch observed: $ACTIVE_BATCH  
Next eligible observed: $NEXT_BATCH

## Purpose

This report was generated by \`scripts/codex-post-pk03-dirty-reconciliation.sh\` after PK03 or before global-train continuation.

The gate preserves worktree evidence and prevents the global train from continuing over unclassified dirty state.

## Evidence Files

- Status: \`$STATUS_FILE\`
- Untracked: \`$UNTRACKED_FILE\`
- Diff: \`$DIFF_FILE\`
- Staged diff: \`$STAGED_DIFF_FILE\`
- Name status: \`$NAME_STATUS_FILE\`

## Dirty Count

\`\`\`text
$DIRTY_COUNT
\`\`\`

## Current Status

\`\`\`text
$(cat "$STATUS_FILE")
\`\`\`

## Required Classification If Dirty

If dirty count is nonzero, classify every dirty file into one of:

1. Expected PK03 output.
2. Expected global-train output before/after PK03.
3. Expected MCP/tooling output from prior prompt.
4. Generated/log artifact that should remain untracked or ignored.
5. Accidental or unsafe change.
6. Unknown / needs human review.

## Recommended Action

EOF

if [[ "$DIRTY_COUNT" == "0" ]]; then
  cat >> "$REPORT" <<EOF
The worktree is clean. The global train may continue after re-reading active batch state.

## EFC Applicability

EFC applicability: not applicable to this generated report unless a later batch uses it as evidence.

## Non-Claims

This gate does not claim build, test, release, device, accessibility, legal/privacy, App Store, TestFlight, or product behavior proof.
EOF
  cp "$REPORT" "$LATEST_REPORT"
  echo "Post-PK03 dirty worktree gate passed: clean worktree. Report: $REPORT"
  exit 0
fi

cat >> "$REPORT" <<EOF
The worktree is dirty. Do not continue the global train until every dirty file is classified and either committed, intentionally left, stashed, ignored, or discarded after approval.

## Proposed Next Command

Run the Codex prompt in \`docs/codex/batches/POST_PK03_Dirty_Worktree_Reconciliation_Gate_Prompt.md\`.

## EFC Applicability

EFC applicability: invoked. Dirty-state reconciliation affects continuation proof, release-claim safety, and source-truth integrity.

## Non-Claims

This gate does not claim build, test, release, device, accessibility, legal/privacy, App Store, TestFlight, or product behavior proof.

## Hard Red

Continuing the global train with this dirty state unclassified is a Hard Red.
EOF

cp "$REPORT" "$LATEST_REPORT"
echo "Post-PK03 dirty worktree gate blocked: $DIRTY_COUNT dirty entries. Report: $REPORT" >&2
exit 86
